package pages_hiperlibertad

import (
	"comprix/app/domain/dto"
)

func (svc Service) GetCategoryLinks() []dto.ScrapperCategoryLink {
	return []dto.ScrapperCategoryLink{
		{Link: "https://www.hiperlibertad.com.ar/almacen/aceites-y-vinagres/aceites/aceites-de-girasol/aceites-de-maiz/aceites-de-oliva/aceites-mezcla/otras-variedades-de-aceites?initialMap=c,c&initialQuery=almacen/aceites-y-vinagres&map=category-1,category-2,category-3,category-3,category-3,category-3,category-3,category-3&page=2", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aceites"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/aderezos", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aderezos"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/aceites-y-vinagres/vinagres?initialMap=c,c&initialQuery=almacen/aceites-y-vinagres&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Vinagres"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/aceites-y-vinagres/acetos?initialMap=c,c&initialQuery=almacen/aceites-y-vinagres&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Acheto"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/arroz-y-legumbres/arroz/arroz-listo?initialMap=c,c&initialQuery=almacen/arroz-y-legumbres&map=category-1,category-2,category-3,category-3", Categories: []string{"Almacén", "Arroz y Legumbres", "Arroz"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/arroz-y-legumbres/legumbres?initialMap=c,c&initialQuery=almacen/arroz-y-legumbres&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Arroz y Legumbres", "Legumbres"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/pastas-secas-y-salsas/fideos-guiseros/fideos-largos/fideos-para-sopas/pastas-secas-rellenas?initialMap=c,c&initialQuery=almacen/pastas-secas-y-salsas&map=category-1,category-2,category-3,category-3,category-3,category-3", Categories: []string{"Almacén", "Pastas secas", "Pastas secas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/sal-pimienta-y-especias/sal?initialMap=c,c&initialQuery=almacen/sal-pimienta-y-especias&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Sal"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/sal-pimienta-y-especias/pimienta?initialMap=c,c&initialQuery=almacen/sal-pimienta-y-especias&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Pimienta"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/sal-pimienta-y-especias/hierbas-y-especias?initialMap=c,c&initialQuery=almacen/sal-pimienta-y-especias&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Especias"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/conservas/conservas-de-carnes?initialMap=c,c&initialQuery=almacen/conservas&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Conservas", "Conserva de carne"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/conservas/conservas-de-frutas?initialMap=c,c&initialQuery=almacen/conservas&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Conservas", "Conserva de frutas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/conservas/conservas-de-pescado?initialMap=c,c&initialQuery=almacen/conservas&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Conservas", "Conserva de pescado"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/conservas/conservas-de-verduras-y-legumbres?initialMap=c,c&initialQuery=almacen/conservas&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Conservas", "Conserva de verduras y legumbres"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/azucar-y-edulcorantes?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Azúcar"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/bizcochuelos-budines-y-magdalenas?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Biscochuelos"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/cacaos?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cacao y Saborizantes"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/cafes?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cafes"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/cereales?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cereales"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/galletitas-dulces?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas dulces"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/galletitas-saladas?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas saladas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/mermeladas-y-dulces?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Mermeladas y dulces"}},
		{Link: "https://www.hiperlibertad.com.ar/pionono?_q=pionono&map=ft", Categories: []string{"Almacén", "Desayunos y Meriendas", "Piononos"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/tes?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Tes"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/desayuno-y-merienda/yerbas?initialMap=c,c&initialQuery=almacen/desayuno-y-merienda&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Desayunos y Meriendas", "Yerbas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/harinas/harinas-comunes-y-leudantes?initialMap=c,c&initialQuery=almacen/harinas&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Harinas", "Harinas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/harinas/avenas-y-semolas?initialMap=c,c&initialQuery=almacen/harinas&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Harinas", "Avenas y Sémolas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/harinas/polentas?initialMap=c,c&initialQuery=almacen/harinas&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Harinas", "Polentas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/harinas/premezclas?initialMap=c,c&initialQuery=almacen/harinas&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Harinas", "Pre mezclas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/panificados/pan-lactal?initialMap=c,c&initialQuery=almacen/panificados&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Panificados", "Lacteados"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/panificados/pan-para-hamburguesas-y-panchos?initialMap=c,c&initialQuery=almacen/panificados&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Panificados", "Pan para hamburguesas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/panificados/tostadas-y-grisines?initialMap=c,c&initialQuery=almacen/panificados&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Panificados", "Tostadas y grisines"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/panificados/pan-rallado-y-rebozadores?initialMap=c,c&initialQuery=almacen/panificados&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Panificados", "Pan rallado y rebozador"}},
		{Link: "https://www.hiperlibertad.com.ar/pan%20integral?_q=pan%20integral&map=ft", Categories: []string{"Almacén", "Panificados", "Integral y Salvado"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/caldos-sopas-y-pure/caldos?initialMap=c,c&initialQuery=almacen/caldos-sopas-y-pure&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Caldos"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/caldos-sopas-y-pure/sopas?initialMap=c,c&initialQuery=almacen/caldos-sopas-y-pure&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Sopas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/caldos-sopas-y-pure/pure?initialMap=c,c&initialQuery=almacen/caldos-sopas-y-pure&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Purés"}},
		{Link: "https://www.hiperlibertad.com.ar/brownies?_q=brownies&map=ft", Categories: []string{"Almacén", "Para preparar", "Brownies"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/para-preparar/bizcochuelos-y-tortas?initialMap=c,c&initialQuery=almacen/para-preparar&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Para preparar", "Tortas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/para-preparar/flanes?initialMap=c,c&initialQuery=almacen/para-preparar&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Para preparar", "Flanes"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/para-preparar/gelatinas?initialMap=c,c&initialQuery=almacen/para-preparar&map=category-1,category-2,category-3", Categories: []string{"Almacén", "Para preparar", "Gelatinas"}},
		{Link: "https://www.hiperlibertad.com.ar/mousse?_q=mousse&map=ft", Categories: []string{"Almacén", "Para preparar", "Mousse"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/snacks/frutas-secas-y-disecadas", Categories: []string{"Almacén", "Snacks", "Frutas secas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/snacks/mani", Categories: []string{"Almacén", "Snacks", "Manís"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/snacks/nachos", Categories: []string{"Almacén", "Snacks", "Nachos"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/snacks/papas-fritas", Categories: []string{"Almacén", "Snacks", "Papas fritas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/snacks/palitos", Categories: []string{"Almacén", "Snacks", "Palitos Salados"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/snacks/pochoclos", Categories: []string{"Almacén", "Snacks", "Pochoclos"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/snacks/otros-snacks", Categories: []string{"Almacén", "Snacks", "Snacks"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/golosinas-y-chocolates/alfajores", Categories: []string{"Almacén", "Golosinas y Chocolates", "Alfajores"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/golosinas-y-chocolates/bombones", Categories: []string{"Almacén", "Golosinas y Chocolates", "Bombones"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/golosinas-y-chocolates/caramelos-y-chicles", Categories: []string{"Almacén", "Golosinas y Chocolates", "Caramelos y chicles"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/golosinas-y-chocolates/chocolates", Categories: []string{"Almacén", "Golosinas y Chocolates", "Chocolates"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/golosinas-y-chocolates/turrones", Categories: []string{"Almacén", "Golosinas y Chocolates", "Turrones"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/cervezas", Categories: []string{"Bebidas", "Cervezas", "Cervezas"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/gaseosas", Categories: []string{"Bebidas", "Gaseosas", "Gaseosas"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/jugos/listos-para-tomar", Categories: []string{"Bebidas", "Jugos", "Listos para tomar"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/jugos/en-polvo", Categories: []string{"Bebidas", "Jugos", "En polvo"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/aguas/aguas-con-gas", Categories: []string{"Bebidas", "Aguas", "Aguas con gas"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/aguas/aguas-sin-gas", Categories: []string{"Bebidas", "Aguas", "Aguas sin gas"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/aguas/aguas-saborizadas", Categories: []string{"Bebidas", "Aguas", "Aguas saborizadas"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/vinos-y-espumantes", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/isotonicas-y-energizantes/isotonicas", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas isotónicas"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/isotonicas-y-energizantes/energizantes", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas energizantes"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/bebidas-blancas-y-licores/licores", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Licores"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/bebidas-blancas-y-licores/whiskys", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Whiskyes"}},
		{Link: "https://www.hiperlibertad.com.ar/bebidas/bebidas-blancas-y-licores/bebidas-blancas", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Bebidas blancas"}},
		{Link: "https://www.hiperlibertad.com.ar/lacteos/dulce-de-leche", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Dulce de leche", "Dulces de leche"}},
		{Link: "https://www.hiperlibertad.com.ar/lacteos/cremas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Cremas", "Cremas"}},
		{Link: "https://www.hiperlibertad.com.ar/lacteos/mantecas-y-margarinas/mantecas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Mantecas"}},
		{Link: "https://www.hiperlibertad.com.ar/lacteos/mantecas-y-margarinas/margarinas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Margarinas"}},
		{Link: "https://www.hiperlibertad.com.ar/lacteos/yogures/bebibles", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures enteros"}},
		{Link: "https://www.hiperlibertad.com.ar/lacteos/yogures/firmes", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures Firmes"}},
		{Link: "https://www.hiperlibertad.com.ar/lacteos/leches/larga-vida", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches larga vida"}},
		{Link: "https://www.hiperlibertad.com.ar/lacteos/leches/leches-vegetales", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches Vegetales"}},
		{Link: "https://www.hiperlibertad.com.ar/lacteos/leches/leches-infantiles", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches Infantiles"}},
		{Link: "https://www.hiperlibertad.com.ar/quesos-y-fiambres/quesos", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos untables"}},
		{Link: "https://www.hiperlibertad.com.ar/quesos-y-fiambres/fiambres", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Fiambres", "Jamónes cocidos"}},
		{Link: "https://www.hiperlibertad.com.ar/quesos-y-fiambres/salchichas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Embutidos", "Salchichas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/aceitunas-y-encurtidos/aceitunas-negras", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Aceitunas"}},
		{Link: "https://www.hiperlibertad.com.ar/almacen/aceitunas-y-encurtidos/aceitunas-verdes", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Aceitunas"}},
		{Link: "https://www.hiperlibertad.com.ar/pickles?_q=pickles&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Pickles"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-capilar/shampoo", Categories: []string{"Perfumería", "Cuidado capilar", "Shampoos"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-capilar/acondicionadores", Categories: []string{"Perfumería", "Cuidado capilar", "Acondicionadores"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-capilar/tratamientos-capilares", Categories: []string{"Perfumería", "Cuidado capilar", "Tratamientos capilares"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-capilar/fijadores", Categories: []string{"Perfumería", "Cuidado capilar", "Fijadores"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-capilar/coloracion", Categories: []string{"Perfumería", "Cuidado capilar", "Coloración"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-oral/pastas-dentales", Categories: []string{"Perfumería", "Cuidado Oral", "Pastas dentales"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-oral/cepillos-dentales", Categories: []string{"Perfumería", "Cuidado Oral", "Cepillos dentales"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-oral/enjuagues-bucales", Categories: []string{"Perfumería", "Cuidado Oral", "Enjuagues bucales"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-oral/accesorios-bucales", Categories: []string{"Perfumería", "Cuidado Oral", "Accesorios bucales"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-personal/cepillos-y-esponjas", Categories: []string{"Perfumería", "Cuidado personal", "Cepillos y esponjas"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-personal/depilacion", Categories: []string{"Perfumería", "Cuidado personal", "Depilación"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-personal/desodorantes-de-hombre", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes de hombres"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-personal/desodorantes-de-mujer", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes de mujeres"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-personal/desodorantes-infantiles", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes infantiles"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-personal/talcos", Categories: []string{"Perfumería", "Cuidado personal", "Talcos"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-personal/jabones", Categories: []string{"Perfumería", "Cuidado personal", "Jabones"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-personal/productos-para-afeitarse", Categories: []string{"Perfumería", "Cuidado personal", "Productos para afeitarse"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-de-la-piel/cremas-corporales", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas corporales"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-de-la-piel/cremas-desmaquillantes", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas desmaquillantes"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-de-la-piel/cremas-faciales", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas faciales"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-de-la-piel/solares-y-postsolares", Categories: []string{"Perfumería", "Cuidado de la piel", "Solares y postsolares"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/cuidado-de-la-piel/maquillajes", Categories: []string{"Perfumería", "Cuidado de la piel", "Maquillajes"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/proteccion-femenina/protectores-diarios", Categories: []string{"Perfumería", "Protección femenina", "Protectores diarios"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/proteccion-femenina/toallitas", Categories: []string{"Perfumería", "Protección femenina", "Toallitas"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/proteccion-femenina/tampones", Categories: []string{"Perfumería", "Protección femenina", "Tampones"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/proteccion-femenina/higiene-intima", Categories: []string{"Perfumería", "Protección femenina", "Higiene íntima"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/farmacia/algodon", Categories: []string{"Perfumería", "Farmacia", "Algodón"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/farmacia/alcohol", Categories: []string{"Perfumería", "Farmacia", "Alcohol"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/farmacia/apositos", Categories: []string{"Perfumería", "Farmacia", "Apósitos"}},
		{Link: "https://www.hiperlibertad.com.ar/perfumeria/farmacia/preservativos", Categories: []string{"Perfumería", "Farmacia", "Preservativos"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/accesorios-de-limpieza/baldes-y-mopas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Baldes y Mopas"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/accesorios-de-limpieza/bolsas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Bolsas"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/accesorios-de-limpieza/broches-y-ganchos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Broches y Ganchos"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/accesorios-de-limpieza/escobas-y-escobillones", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Escobas y escobillones"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/accesorios-de-limpieza/escobillas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Escobillas"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/accesorios-de-limpieza/esponjas-y-guantes", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Esponjas y Guantes"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/accesorios-de-limpieza/panos-multiuso", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Paños multiusos"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/accesorios-de-limpieza/secadores-y-cepillos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Secadores y Cepillos"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/accesorios-de-limpieza/trapos-de-piso", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Trapos de piso"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/calzado/brillos-y-revividores", Categories: []string{"Limpieza", "Calzado", "Brillos y revividores"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/calzado/limpiadores", Categories: []string{"Limpieza", "Calzado", "Limpiadores"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/calzado/pomadas", Categories: []string{"Limpieza", "Calzado", "Pomadas para calzado"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/desodorantes-de-ambiente/aromatizantes", Categories: []string{"Limpieza", "Deshodorantes de ambiente", "Aromatizantes"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/desodorantes-de-ambiente/desodorantes-y-desinfentantes", Categories: []string{"Limpieza", "Deshodorantes de ambiente", "Deshodorantes y desinfectantes"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/insecticidas/aerosoles", Categories: []string{"Limpieza", "Incecticidas", "Aerosoles"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/insecticidas/cebos-y-pastillas", Categories: []string{"Limpieza", "Incecticidas", "Cebos, Bolillas y Pastillas"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/insecticidas/repelentes", Categories: []string{"Limpieza", "Incecticidas", "Repelentes"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/insecticidas/tabletas-y-difusores", Categories: []string{"Limpieza", "Incecticidas", "Tabletas y difusores"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/lavandina/lavandina-en-gel", Categories: []string{"Limpieza", "Lavandinas", "Lavandinas en gel"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/lavandina/lavandina-liquida", Categories: []string{"Limpieza", "Lavandinas", "Lavandinas líquidas"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-bano/desinfectantes", Categories: []string{"Limpieza", "Limpieza de baño", "Desinfectantes"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-bano/destapa-canerias", Categories: []string{"Limpieza", "Limpieza de baño", "Destapa cañerías"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-bano/pastillas-y-bloques", Categories: []string{"Limpieza", "Limpieza de baño", "Pastillas y bloques"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-cocina/detergentes", Categories: []string{"Limpieza", "Limpieza de cocina", "Detergentes"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-cocina/escarbadientes", Categories: []string{"Limpieza", "Limpieza de cocina", "Escarbadientes"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-cocina/fosforos-y-encendedores", Categories: []string{"Limpieza", "Limpieza de cocina", "Fósforos y encendedores"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-cocina/jabon-lavavajillas", Categories: []string{"Limpieza", "Limpieza de cocina", "Jabón Lavavajillas"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-cocina/limpiadores", Categories: []string{"Limpieza", "Limpieza de cocina", "LIimpiadores"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-cocina/velas", Categories: []string{"Limpieza", "Limpieza de cocina", "Velas"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-cocina/bolsas-y-film", Categories: []string{"Limpieza", "Limpieza de cocina", "Bolsas y films"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/cuidado-de-la-ropa/jabon-en-pan", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón en pan"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/cuidado-de-la-ropa/jabon-en-polvo", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón en polvo"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/cuidado-de-la-ropa/jabon-liquido", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón líquido"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/cuidado-de-la-ropa/suavizantes", Categories: []string{"Limpieza", "Cuidados de la ropa", "Suavizantes"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/cuidado-de-la-ropa/quitamanchas", Categories: []string{"Limpieza", "Cuidados de la ropa", "Quita Manchas"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/cuidado-de-la-ropa/perfumantes", Categories: []string{"Limpieza", "Cuidados de la ropa", "Perfumantes"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/cuidado-de-la-ropa/aprestos-y-blanqueadores", Categories: []string{"Limpieza", "Cuidados de la ropa", "Apréstos"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-pisos-y-muebles/ceras-y-autobrillos", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Ceras y autobrillos"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-pisos-y-muebles/limpiadores-de-piso", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Limpiadores de piso"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/limpieza-de-pisos-y-muebles/lustramuebles", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Lustra muebles"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/papeles/panuelos", Categories: []string{"Limpieza", "Papeles", "Pañuelos"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/papeles/papel-higienico", Categories: []string{"Limpieza", "Papeles", "Papeles higiénicos"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/papeles/rollos-de-cocina", Categories: []string{"Limpieza", "Papeles", "Rollos de cocina"}},
		{Link: "https://www.hiperlibertad.com.ar/limpieza/papeles/servilletas", Categories: []string{"Limpieza", "Papeles", "Servilletas"}},
		{Link: "https://www.hiperlibertad.com.ar/mascotas/alimentos", Categories: []string{"Mascotas", "Alimentos", "Alimentos"}},
	}
}
