package pages_alem

import (
	"comprix/app/domain/dto"
)

func (svc Service) GetCategoryLinks() []dto.ScrapperCategoryLink {
	return []dto.ScrapperCategoryLink{
		{Link: "17", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aceites"}},
		{Link: "20", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aderezos"}},
		{Link: "168", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Vinagres"}},
		{Link: "348", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Acheto"}},
		{Link: "217", Categories: []string{"Almacén", "Arroz y Legumbres", "Arroz"}},
		{Link: "15", Categories: []string{"Almacén", "Arroz y Legumbres", "Arroz"}},
		{Link: "53", Categories: []string{"Almacén", "Arroz y Legumbres", "Legumbres"}},
		{Link: "180", Categories: []string{"Almacén", "Pastas secas", "Pastas secas"}},
		{Link: "149", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Sal"}},
		{Link: "28", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Especias"}},
		{Link: "13", Categories: []string{"Almacén", "Conservas", "Conserva de pescado"}},
		{Link: "5", Categories: []string{"Almacén", "Conservas", "Conserva de verduras y legumbres"}},
		{Link: "185", Categories: []string{"Almacén", "Desayunos y Meriendas", "Azúcar"}},
		{Link: "39", Categories: []string{"Almacén", "Desayunos y Meriendas", "Edulcorante"}},
		{Link: "100", Categories: []string{"Almacén", "Desayunos y Meriendas", "Budines"}},
		{Link: "344", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cacao y Saborizantes"}},
		{Link: "111", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cafes"}},
		{Link: "345", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cafes"}},
		{Link: "231", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cafes"}},
		{Link: "336", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cereales"}},
		{Link: "337", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas dulces"}},
		{Link: "210", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas saladas"}},
		{Link: "109", Categories: []string{"Almacén", "Desayunos y Meriendas", "Mermeladas y dulces"}},
		{Link: "334", Categories: []string{"Almacén", "Desayunos y Meriendas", "Mermeladas y dulces"}},
		{Link: "335", Categories: []string{"Almacén", "Desayunos y Meriendas", "Mermeladas y dulces"}},
		{Link: "55", Categories: []string{"Almacén", "Desayunos y Meriendas", "Mermeladas y dulces"}},
		{Link: "162", Categories: []string{"Almacén", "Desayunos y Meriendas", "Tes"}},
		{Link: "174", Categories: []string{"Almacén", "Desayunos y Meriendas", "Yerbas"}},
		{Link: "73", Categories: []string{"Almacén", "Harinas", "Harinas"}},
		{Link: "192", Categories: []string{"Almacén", "Harinas", "Harinas"}},
		{Link: "356", Categories: []string{"Almacén", "Harinas", "Harinas"}},
		{Link: "19", Categories: []string{"Almacén", "Harinas", "Avenas y Sémolas"}},
		{Link: "358", Categories: []string{"Almacén", "Harinas", "Avenas y Sémolas"}},
		{Link: "123", Categories: []string{"Almacén", "Panificados", "Lacteados"}},
		{Link: "147", Categories: []string{"Almacén", "Panificados", "Pan rallado y rebozador"}},
		{Link: "27", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Caldos"}},
		{Link: "144", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Purés"}},
		{Link: "221", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Purés"}},
		{Link: "304", Categories: []string{"Almacén", "Para preparar", "Flanes"}},
		{Link: "202", Categories: []string{"Almacén", "Snacks", "Frutas secas"}},
		{Link: "183", Categories: []string{"Almacén", "Snacks", "Snacks"}},
		{Link: "400", Categories: []string{"Almacén", "Golosinas y Chocolates", "Bombones"}},
		{Link: "187", Categories: []string{"Almacén", "Golosinas y Chocolates", "Caramelos y chicles"}},
		{Link: "126", Categories: []string{"Almacén", "Golosinas y Chocolates", "Turrones"}},
		{Link: "186", Categories: []string{"Bebidas", "Cervezas", "Cervezas"}},
		{Link: "331", Categories: []string{"Bebidas", "Cervezas", "Cervezas"}},
		{Link: "182", Categories: []string{"Bebidas", "Gaseosas", "Gaseosas"}},
		{Link: "79", Categories: []string{"Bebidas", "Jugos", "Listos para tomar"}},
		{Link: "228", Categories: []string{"Bebidas", "Jugos", "Listos para tomar"}},
		{Link: "208", Categories: []string{"Bebidas", "Aguas", "Aguas con gas"}},
		{Link: "207", Categories: []string{"Bebidas", "Aguas", "Aguas sin gas"}},
		{Link: "164", Categories: []string{"Bebidas", "Aguas", "Aguas saborizadas"}},
		{Link: "169", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "230", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "188", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "189", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "32", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "26", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "82", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "227", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas isotónicas"}},
		{Link: "22", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas energizantes"}},
		{Link: "87", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Licores"}},
		{Link: "172", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Whiskyes"}},
		{Link: "36", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Whiskyes"}},
		{Link: "48", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Whiskyes"}},
		{Link: "2", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Bebidas blancas"}},
		{Link: "332", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Dulce de leche", "Dulces de leche"}},
		{Link: "214", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Cremas", "Cremas"}},
		{Link: "47", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Cremas", "Cremas"}},
		{Link: "97", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Mantecas"}},
		{Link: "101", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Margarinas"}},
		{Link: "175", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures enteros"}},
		{Link: "346", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures enteros"}},
		{Link: "218", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches larga vida"}},
		{Link: "315", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos untables"}},
		{Link: "328", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos rallados"}},
		{Link: "143", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos Port salut"}},
		{Link: "300", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos cremosos"}},
		{Link: "201", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos en fetas"}},
		{Link: "314", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos en fetas"}},
		{Link: "313", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos en fetas"}},
		{Link: "353", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos en fetas"}},
		{Link: "352", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos en fetas"}},
		{Link: "355", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos en fetas"}},
		{Link: "311", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos en fetas"}},
		{Link: "76", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Fiambres", "Jamónes cocidos"}},
		{Link: "77", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Fiambres", "Jamónes cocidos"}},
		{Link: "74", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Fiambres", "Jamónes crudos"}},
		{Link: "152", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Embutidos", "Salchichas"}},
		{Link: "153", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Embutidos", "Salchichas"}},
		{Link: "420", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Aceitunas"}},
		{Link: "360", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Aceitunas"}},
		{Link: "135", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Pickles"}},
		{Link: "131", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Pickles"}},
		{Link: "130", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Pickles"}},
		{Link: "600", Categories: []string{"Perfumería", "Cuidado capilar", "Shampoos"}},
		{Link: "601", Categories: []string{"Perfumería", "Cuidado capilar", "Acondicionadores"}},
		{Link: "631", Categories: []string{"Perfumería", "Cuidado Oral", "Pastas dentales"}},
		{Link: "630", Categories: []string{"Perfumería", "Cuidado Oral", "Cepillos dentales"}},
		{Link: "620", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes de mujeres"}},
		{Link: "621", Categories: []string{"Perfumería", "Cuidado personal", "Jabones"}},
		{Link: "633", Categories: []string{"Perfumería", "Cuidado personal", "Productos para afeitarse"}},
		{Link: "634", Categories: []string{"Perfumería", "Cuidado personal", "Productos para afeitarse"}},
		{Link: "610", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas corporales"}},
		{Link: "611", Categories: []string{"Perfumería", "Cuidado de la piel", "Solares y postsolares"}},
		{Link: "622", Categories: []string{"Perfumería", "Protección femenina", "Protectores diarios"}},
		{Link: "640", Categories: []string{"Perfumería", "Farmacia", "Algodón"}},
		{Link: "641", Categories: []string{"Perfumería", "Farmacia", "Alcohol"}},
		{Link: "639", Categories: []string{"Perfumería", "Farmacia", "Apósitos"}},
		{Link: "478", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Baldes y Mopas"}},
		{Link: "452", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Bolsas"}},
		{Link: "454", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Escobas y escobillones"}},
		{Link: "476", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Esponjas y Guantes"}},
		{Link: "453", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Trapos de piso"}},
		{Link: "642", Categories: []string{"Limpieza", "Calzado", "Brillos y revividores"}},
		{Link: "456", Categories: []string{"Limpieza", "Deshodorantes de ambiente", "Deshodorantes y desinfectantes"}},
		{Link: "455", Categories: []string{"Limpieza", "Incecticidas", "Aerosoles"}},
		{Link: "469", Categories: []string{"Limpieza", "Lavandinas", "Lavandinas en gel"}},
		{Link: "648", Categories: []string{"Limpieza", "Limpieza de baño", "Desinfectantes"}},
		{Link: "477", Categories: []string{"Limpieza", "Limpieza de cocina", "Detergentes"}},
		{Link: "473", Categories: []string{"Limpieza", "Limpieza de cocina", "Detergentes"}},
		{Link: "466", Categories: []string{"Limpieza", "Limpieza de cocina", "Fósforos y encendedores"}},
		{Link: "467", Categories: []string{"Limpieza", "Limpieza de cocina", "LIimpiadores"}},
		{Link: "643", Categories: []string{"Limpieza", "Limpieza de cocina", "LIimpiadores"}},
		{Link: "468", Categories: []string{"Limpieza", "Limpieza de cocina", "LIimpiadores"}},
		{Link: "461", Categories: []string{"Limpieza", "Limpieza de cocina", "LIimpiadores"}},
		{Link: "462", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón en pan"}},
		{Link: "463", Categories: []string{"Limpieza", "Cuidados de la ropa", "Suavizantes"}},
		{Link: "450", Categories: []string{"Limpieza", "Papeles", "Papeles higiénicos"}},
		{Link: "451", Categories: []string{"Limpieza", "Papeles", "Servilletas"}},
	}
}
