package pages_masonline

import (
	"comprix/app/domain/dto"
)

func (svc Service) GetCategoryLinks() []dto.ScrapperCategoryLink {
	return []dto.ScrapperCategoryLink{
		{Link: "https://www.masonline.com.ar/aceites-vinagres-y-aderezos/aceites", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aceites"}},
		{Link: "https://www.masonline.com.ar/aceites-vinagres-y-aderezos/aderezos", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aderezos"}},
		{Link: "https://www.masonline.com.ar/aceites-vinagres-y-aderezos/vinagres-y-aceto?initialMap=c,c&initialQuery=aceites-vinagres-y-aderezos/vinagres-y-aceto&map=category-1,category-2,category-3,category-3,category-3,category-3&query=/aceites-vinagres-y-aderezos/vinagres-y-aceto/otros-vinagres/vinagre-de-alcohol/vinagre-de-manzana/vinagre-de-vino&searchState", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Vinagres"}},
		{Link: "https://www.masonline.com.ar/aceites-vinagres-y-aderezos/vinagres-y-aceto?initialMap=c,c&initialQuery=aceites-vinagres-y-aderezos/vinagres-y-aceto&map=category-1,category-2,category-3&query=/aceites-vinagres-y-aderezos/vinagres-y-aceto/aceto&searchState", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Acheto"}},
		{Link: "https://www.masonline.com.ar/arroz-legumbres-y-pastas/arroz", Categories: []string{"Almacén", "Arroz y Legumbres", "Arroz"}},
		{Link: "https://www.masonline.com.ar/arroz-legumbres-y-pastas/legumbres", Categories: []string{"Almacén", "Arroz y Legumbres", "Legumbres"}},
		{Link: "https://www.masonline.com.ar/arroz-legumbres-y-pastas/pastas-secas", Categories: []string{"Almacén", "Pastas secas", "Pastas secas"}},
		{Link: "https://www.masonline.com.ar/condimentos-y-especias/sal-y-pimienta?initialMap=c,c&initialQuery=condimentos-y-especias/sal-y-pimienta&map=category-1,category-2,category-3&query=/condimentos-y-especias/sal-y-pimienta/sal&searchState", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Sal"}},
		{Link: "https://www.masonline.com.ar/condimentos-y-especias/sal-y-pimienta?initialMap=c,c&initialQuery=condimentos-y-especias/sal-y-pimienta&map=category-1,category-2,category-3&query=/condimentos-y-especias/sal-y-pimienta/pimienta&searchState", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Pimienta"}},
		{Link: "https://www.masonline.com.ar/condimentos-y-especias/especias", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Especias"}},
		{Link: "https://www.masonline.com.ar/conservas-y-enlatados/conservas?initialMap=c,c&initialQuery=conservas-y-enlatados/conservas&map=category-1,category-2,category-3&query=/conservas-y-enlatados/conservas/conservas-de-frutas&searchState", Categories: []string{"Almacén", "Conservas", "Conserva de frutas"}},
		{Link: "https://www.masonline.com.ar/conservas-y-enlatados/conservas?initialMap=c,c&initialQuery=conservas-y-enlatados/conservas&map=category-1,category-2,category-3&query=/conservas-y-enlatados/conservas/conservas-de-pescado&searchState", Categories: []string{"Almacén", "Conservas", "Conserva de pescado"}},
		{Link: "https://www.masonline.com.ar/conservas-y-enlatados/conservas?initialMap=c,c&initialQuery=conservas-y-enlatados/conservas&map=category-1,category-2,category-3&query=/conservas-y-enlatados/conservas/conservas-de-verdura-y-legumbres&searchState", Categories: []string{"Almacén", "Conservas", "Conserva de verduras y legumbres"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/endulzantes/azucar", Categories: []string{"Almacén", "Desayunos y Meriendas", "Azúcar"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas?initialMap=c&initialQuery=desayunos-y-meriendas&map=category-1,category-3&query=/desayunos-y-meriendas/edulcorante&searchState", Categories: []string{"Almacén", "Desayunos y Meriendas", "Edulcorante"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/budines-magdalenas-y-otros?initialMap=c,c&initialQuery=desayunos-y-meriendas/budines-magdalenas-y-otros&map=category-1,category-2,category-3&query=/desayunos-y-meriendas/budines-magdalenas-y-otros/bizcochuelos&searchState", Categories: []string{"Almacén", "Desayunos y Meriendas", "Biscochuelos"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/budines-magdalenas-y-otros?initialMap=c,c&initialQuery=desayunos-y-meriendas/budines-magdalenas-y-otros&map=category-1,category-2,category-3&query=/desayunos-y-meriendas/budines-magdalenas-y-otros/budines&searchState", Categories: []string{"Almacén", "Desayunos y Meriendas", "Budines"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/budines-magdalenas-y-otros?initialMap=c,c&initialQuery=desayunos-y-meriendas/budines-magdalenas-y-otros&map=category-1,category-2,category-3&query=/desayunos-y-meriendas/budines-magdalenas-y-otros/magdalenas&searchState", Categories: []string{"Almacén", "Desayunos y Meriendas", "Magdalenas"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/cacao", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cacao y Saborizantes"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/cafe", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cafes"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/cereales", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cereales"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/galletitas-dulces", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas dulces"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/galletitas-saladas", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas saladas"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/mermeladas-y-untables", Categories: []string{"Almacén", "Desayunos y Meriendas", "Mermeladas y dulces"}},
		{Link: "https://www.masonline.com.ar/pionono?_q=pionono&map=ft", Categories: []string{"Almacén", "Desayunos y Meriendas", "Piononos"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/te", Categories: []string{"Almacén", "Desayunos y Meriendas", "Tes"}},
		{Link: "https://www.masonline.com.ar/desayunos-y-meriendas/yerbas", Categories: []string{"Almacén", "Desayunos y Meriendas", "Yerbas"}},
		{Link: "https://www.masonline.com.ar/harinas?initialMap=c&initialQuery=harinas&map=category-1,category-2,category-2,category-2&query=/harinas/harina-de-maiz/harina-de-trigo/otras-harinas&searchState", Categories: []string{"Almacén", "Harinas", "Harinas"}},
		{Link: "https://www.masonline.com.ar/harinas?initialMap=c&initialQuery=harinas&map=category-1,category-2,category-2&query=/harinas/avena/semola&searchState", Categories: []string{"Almacén", "Harinas", "Avenas y Sémolas"}},
		{Link: "https://www.masonline.com.ar/harinas?initialMap=c&initialQuery=harinas&map=category-1,category-2&query=/harinas/premezclas&searchState", Categories: []string{"Almacén", "Harinas", "Pre mezclas"}},
		{Link: "https://www.masonline.com.ar/pan%20lacteado?_q=pan%20lacteado&map=ft", Categories: []string{"Almacén", "Panificados", "Lacteados"}},
		{Link: "https://www.masonline.com.ar/panificados/pan-para-hamburguesas-y-panchos?initialMap=c,c&initialQuery=panificados/pan-para-hamburguesas-y-panchos&map=category-1,category-2,category-3&query=/panificados/pan-para-hamburguesas-y-panchos/pan-para-hamburguesa&searchState", Categories: []string{"Almacén", "Panificados", "Pan para hamburguesas"}},
		{Link: "https://www.masonline.com.ar/panificados/pan-para-hamburguesas-y-panchos?initialMap=c,c&initialQuery=panificados/pan-para-hamburguesas-y-panchos&map=category-1,category-2,category-3&query=/panificados/pan-para-hamburguesas-y-panchos/pan-para-panchos&searchState", Categories: []string{"Almacén", "Panificados", "Pan para panchos"}},
		{Link: "https://www.masonline.com.ar/tostadas?_q=tostadas&map=ft", Categories: []string{"Almacén", "Panificados", "Tostadas y grisines"}},
		{Link: "https://www.masonline.com.ar/panificados/pan-rallado-y-rebozadores", Categories: []string{"Almacén", "Panificados", "Pan rallado y rebozador"}},
		{Link: "https://www.masonline.com.ar/pan%20integral?_q=pan%20integral&map=ft", Categories: []string{"Almacén", "Panificados", "Integral y Salvado"}},
		{Link: "https://www.masonline.com.ar/caldos-sopas-y-pure/caldos", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Caldos"}},
		{Link: "https://www.masonline.com.ar/caldos-sopas-y-pure/sopas", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Sopas"}},
		{Link: "https://www.masonline.com.ar/caldos-sopas-y-pure/pure", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Purés"}},
		{Link: "https://www.masonline.com.ar/brownie?_q=brownie&map=ft", Categories: []string{"Almacén", "Para preparar", "Brownies"}},
		{Link: "https://www.masonline.com.ar/tortas?_q=tortas&map=ft", Categories: []string{"Almacén", "Para preparar", "Tortas"}},
		{Link: "https://www.masonline.com.ar/flanes?_q=flanes&map=ft", Categories: []string{"Almacén", "Para preparar", "Flanes"}},
		{Link: "https://www.masonline.com.ar/gelatinas?_q=gelatinas&map=ft", Categories: []string{"Almacén", "Para preparar", "Gelatinas"}},
		{Link: "https://www.masonline.com.ar/mousse?_q=Mousse&map=ft", Categories: []string{"Almacén", "Para preparar", "Mousse"}},
		{Link: "https://www.masonline.com.ar/snacks?initialMap=c&initialQuery=snacks&map=category-1,category-3&query=/snacks/frutos-secos-mani-y-semillas&searchState", Categories: []string{"Almacén", "Snacks", "Frutas secas"}},
		{Link: "https://www.masonline.com.ar/frutos%20secos?_q=frutos%20secos&fuzzy=0&initialMap=ft&initialQuery=frutos%20secos&map=category-3,ft&operator=and&query=/frutos-secos-y-semillas/frutos%20secos&searchState", Categories: []string{"Almacén", "Snacks", "Manís"}},
		{Link: "https://www.masonline.com.ar/nacho?_q=nacho&fuzzy=0&initialMap=ft&initialQuery=nacho&map=category-3,ft&operator=and&query=/nachos/nacho&searchState", Categories: []string{"Almacén", "Snacks", "Nachos"}},
		{Link: "https://www.masonline.com.ar/snacks?initialMap=c&initialQuery=snacks&map=category-1,category-3&query=/snacks/papas-fritas&searchState", Categories: []string{"Almacén", "Snacks", "Papas fritas"}},
		{Link: "https://www.masonline.com.ar/snacks?initialMap=c&initialQuery=snacks&map=category-1,category-3&query=/snacks/palitos&searchState", Categories: []string{"Almacén", "Snacks", "Palitos Salados"}},
		{Link: "https://www.masonline.com.ar/pochoclos?_q=pochoclos&map=ft", Categories: []string{"Almacén", "Snacks", "Pochoclos"}},
		{Link: "https://www.masonline.com.ar/3454?initialMap=productClusterIds&initialQuery=3454&map=category-2,productclusternames&query=/alfajores/almacen&searchState", Categories: []string{"Almacén", "Golosinas y Chocolates", "Alfajores"}},
		{Link: "https://www.masonline.com.ar/bombones?_q=bombones&map=ft", Categories: []string{"Almacén", "Golosinas y Chocolates", "Bombones"}},
		{Link: "https://www.masonline.com.ar/caramelo?_q=caramelo&map=ft", Categories: []string{"Almacén", "Golosinas y Chocolates", "Caramelos y chicles"}},
		{Link: "https://www.masonline.com.ar/chocolate?_q=chocolate&fuzzy=0&initialMap=ft&initialQuery=chocolate&map=category-2,ft&operator=and&query=/chocolates/chocolate&searchState", Categories: []string{"Almacén", "Golosinas y Chocolates", "Chocolates"}},
		{Link: "https://www.masonline.com.ar/turron?_q=turron&map=ft", Categories: []string{"Almacén", "Golosinas y Chocolates", "Turrones"}},
		{Link: "https://www.masonline.com.ar/cervezas", Categories: []string{"Bebidas", "Cervezas", "Cervezas"}},
		{Link: "https://www.masonline.com.ar/gaseosas", Categories: []string{"Bebidas", "Gaseosas", "Gaseosas"}},
		{Link: "https://www.masonline.com.ar/3433?initialMap=productClusterIds&initialQuery=3433&map=category-2,productclusternames&order=OrderByTopSaleDESC&query=/jugos-listos/bebidas&searchState", Categories: []string{"Bebidas", "Jugos", "Listos para tomar"}},
		{Link: "https://www.masonline.com.ar/3433?initialMap=productClusterIds&initialQuery=3433&map=category-2,productclusternames&order=OrderByTopSaleDESC&query=/en-polvo/bebidas&searchState", Categories: []string{"Bebidas", "Jugos", "En polvo"}},
		{Link: "https://www.masonline.com.ar/aguas/agua-con-gas", Categories: []string{"Bebidas", "Aguas", "Aguas con gas"}},
		{Link: "https://www.masonline.com.ar/aguas/agua-sin-gas", Categories: []string{"Bebidas", "Aguas", "Aguas sin gas"}},
		{Link: "https://www.masonline.com.ar/aguas/agua-saborizada", Categories: []string{"Bebidas", "Aguas", "Aguas saborizadas"}},
		{Link: "https://www.masonline.com.ar/vinos-y-espumantes", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "https://www.masonline.com.ar/bebidas-isotonicas-y-energizantes?initialMap=c&initialQuery=bebidas-isotonicas-y-energizantes&map=category-1,category-2&query=/bebidas-isotonicas-y-energizantes/isotonicas&searchState", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas isotónicas"}},
		{Link: "https://www.masonline.com.ar/bebidas-isotonicas-y-energizantes?initialMap=c&initialQuery=bebidas-isotonicas-y-energizantes&map=category-1,category-2&query=/bebidas-isotonicas-y-energizantes/energizantes&searchState", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas energizantes"}},
		{Link: "https://www.masonline.com.ar/bebidas-blancas-licores-y-whiskys?initialMap=c&initialQuery=bebidas-blancas-licores-y-whiskys&map=category-1,category-2&query=/bebidas-blancas-licores-y-whiskys/licores&searchState", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Licores"}},
		{Link: "https://www.masonline.com.ar/bebidas-blancas-licores-y-whiskys?initialMap=c&initialQuery=bebidas-blancas-licores-y-whiskys&map=category-1,category-2&query=/bebidas-blancas-licores-y-whiskys/whiskys&searchState", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Whiskyes"}},
		{Link: "https://www.masonline.com.ar/bebidas-blancas-licores-y-whiskys?initialMap=c&initialQuery=bebidas-blancas-licores-y-whiskys&map=category-1,category-2,category-2,category-2&query=/bebidas-blancas-licores-y-whiskys/gin/tequila/vodka&searchState", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Bebidas blancas"}},
		{Link: "https://www.masonline.com.ar/dulce%20leche?_q=dulce%20leche&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Dulce de leche", "Dulces de leche"}},
		{Link: "https://www.masonline.com.ar/crema/lacteos?map=ft,departamento", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Cremas", "Cremas"}},
		{Link: "https://www.masonline.com.ar/lacteos/mantecas-y-margarinas?initialMap=c,c&initialQuery=lacteos/mantecas-y-margarinas&map=category-1,category-2,category-3&query=/lacteos/mantecas-y-margarinas/manteca&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Mantecas"}},
		{Link: "https://www.masonline.com.ar/lacteos/mantecas-y-margarinas?initialMap=c,c&initialQuery=lacteos/mantecas-y-margarinas&map=category-1,category-2,category-3&query=/lacteos/mantecas-y-margarinas/margarina&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Margarinas"}},
		{Link: "https://www.masonline.com.ar/lacteos/yogures?initialMap=c,c&initialQuery=lacteos/yogures&map=category-1,category-2,category-3&query=/lacteos/yogures/enteros&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures enteros"}},
		{Link: "https://www.masonline.com.ar/lacteos/yogures?initialMap=c,c&initialQuery=lacteos/yogures&map=category-1,category-2,category-3&query=/lacteos/yogures/descremados&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures descremados"}},
		{Link: "https://www.masonline.com.ar/yogurt%20firme?_q=yogurt%20firme&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures Firmes"}},
		{Link: "https://www.masonline.com.ar/leche%20larga%20vida?_q=leche%20larga%20vida&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches larga vida"}},
		{Link: "https://www.masonline.com.ar/lacteos/leches?initialMap=c,c&initialQuery=lacteos/leches&map=category-1,category-2,category-3&query=/lacteos/leches/bebidas-vegetales&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches Vegetales"}},
		{Link: "https://www.masonline.com.ar/lacteos/leches-infantiles", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches Infantiles"}},
		{Link: "https://www.masonline.com.ar/quesos/quesos-crema-y-untables", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos untables"}},
		{Link: "https://www.masonline.com.ar/quesos/rallados", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos rallados"}},
		{Link: "https://www.masonline.com.ar/quesos/cremosos-y-port-salut", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos Port salut"}},
		{Link: "https://www.masonline.com.ar/quesos/ricota", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Ricotas"}},
		{Link: "https://www.masonline.com.ar/queso%20fetas?_q=queso%20fetas&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos en fetas"}},
		{Link: "https://www.masonline.com.ar/jamon?_q=jamon&fuzzy=0&initialMap=ft&initialQuery=jamon&map=category-3,ft&operator=and&query=/jamon-cocido-y-paleta/jamon&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Fiambres", "Jamónes cocidos"}},
		{Link: "https://www.masonline.com.ar/salchicha/salchichas?map=ft,sub-categoria", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Embutidos", "Salchichas"}},
		{Link: "https://www.masonline.com.ar/aceitunas?_q=aceitunas&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Aceitunas"}},
		{Link: "https://www.masonline.com.ar/pickles?_q=pickles&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Pickles"}},
		{Link: "https://www.masonline.com.ar/cuidado-del-cabello/shampoo", Categories: []string{"Perfumería", "Cuidado capilar", "Shampoos"}},
		{Link: "https://www.masonline.com.ar/cuidado-del-cabello/acondicionador", Categories: []string{"Perfumería", "Cuidado capilar", "Acondicionadores"}},
		{Link: "https://www.masonline.com.ar/cuidado-del-cabello/tratamiento-capilar", Categories: []string{"Perfumería", "Cuidado capilar", "Tratamientos capilares"}},
		{Link: "https://www.masonline.com.ar/cuidado-del-cabello/fijacion-y-accesorios", Categories: []string{"Perfumería", "Cuidado capilar", "Fijadores"}},
		{Link: "https://www.masonline.com.ar/cuidado-del-cabello/coloracion", Categories: []string{"Perfumería", "Cuidado capilar", "Coloración"}},
		{Link: "https://www.masonline.com.ar/cuidado-oral/crema-dental", Categories: []string{"Perfumería", "Cuidado Oral", "Pastas dentales"}},
		{Link: "https://www.masonline.com.ar/cuidado-oral/cepillos-dentales", Categories: []string{"Perfumería", "Cuidado Oral", "Cepillos dentales"}},
		{Link: "https://www.masonline.com.ar/cuidado-oral/enjuague-bucal", Categories: []string{"Perfumería", "Cuidado Oral", "Enjuagues bucales"}},
		{Link: "https://www.masonline.com.ar/cuidado-oral/hilo-dental-y-adhesivos", Categories: []string{"Perfumería", "Cuidado Oral", "Accesorios bucales"}},
		{Link: "https://www.masonline.com.ar/cuidado-personal/afeitado-y-depilacion?initialMap=c,c&initialQuery=cuidado-personal/afeitado-y-depilacion&map=category-1,category-2,category-3,category-3,category-3,category-3&query=/cuidado-personal/afeitado-y-depilacion/bandas-depiladoras/cera-depilatoria/cremas-depilatorias/pinzas-de-depilar&searchState", Categories: []string{"Perfumería", "Cuidado personal", "Depilación"}},
		{Link: "https://www.masonline.com.ar/cuidado-personal/desodorantes-y-antitranspirantes?initialMap=c,c&initialQuery=cuidado-personal/desodorantes-y-antitranspirantes&map=category-1,category-2,category-3&query=/cuidado-personal/desodorantes-y-antitranspirantes/desodorantes-y-antitranspirantes-hombre&searchState", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes de hombres"}},
		{Link: "https://www.masonline.com.ar/cuidado-personal/desodorantes-y-antitranspirantes?initialMap=c,c&initialQuery=cuidado-personal/desodorantes-y-antitranspirantes&map=category-1,category-2,category-3&query=/cuidado-personal/desodorantes-y-antitranspirantes/desodorantes-y-antitranspirantes-mujer&searchState", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes de mujeres"}},
		{Link: "https://www.masonline.com.ar/cuidado-personal/desodorantes-y-antitranspirantes?initialMap=c,c&initialQuery=cuidado-personal/desodorantes-y-antitranspirantes&map=category-1,category-2,category-3&query=/cuidado-personal/desodorantes-y-antitranspirantes/desodorantes-y-antitranspirantes-infantiles&searchState", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes infantiles"}},
		{Link: "https://www.masonline.com.ar/talco?map=ft&_q=talco", Categories: []string{"Perfumería", "Cuidado personal", "Talcos"}},
		{Link: "https://www.masonline.com.ar/jabon?_q=jabon&fuzzy=0&initialMap=ft&initialQuery=jabon&map=category-1,ft&operator=and&query=/cuidado-personal/jabon&searchState", Categories: []string{"Perfumería", "Cuidado personal", "Jabones"}},
		{Link: "https://www.masonline.com.ar/cuidado-personal/afeitado-y-depilacion?initialMap=c,c&initialQuery=cuidado-personal/afeitado-y-depilacion&map=category-1,category-2,category-3,category-3&query=/cuidado-personal/afeitado-y-depilacion/espuma-de-afeitar-y-after-shave/maquinas-de-afeitar&searchState", Categories: []string{"Perfumería", "Cuidado personal", "Productos para afeitarse"}},
		{Link: "https://www.masonline.com.ar/crema%20corporal/cuidado-corporal?map=ft,categoria", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas corporales"}},
		{Link: "https://www.masonline.com.ar/maquillaje?_q=maquillaje&initialMap=c&initialQuery=maquillaje&map=category-1,category-2&query=/maquillaje/desmaquillantes&searchState", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas desmaquillantes"}},
		{Link: "https://www.masonline.com.ar/crema%20facial?_q=crema%20facial&fuzzy=0&initialMap=ft&initialQuery=crema%20facial&map=category-1,ft&operator=and&query=/cuidado-de-la-piel/crema%20facial&searchState", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas faciales"}},
		{Link: "https://www.masonline.com.ar/cuidado-de-la-piel/protectores-solares", Categories: []string{"Perfumería", "Cuidado de la piel", "Solares y postsolares"}},
		{Link: "https://www.masonline.com.ar/maquillaje?initialMap=c&initialQuery=maquillaje&map=category-1,category-2,category-2&query=/maquillaje/ojos/rostro&searchState", Categories: []string{"Perfumería", "Cuidado de la piel", "Maquillajes"}},
		{Link: "https://www.masonline.com.ar/proteccion-femenina/protectores-diarios", Categories: []string{"Perfumería", "Protección femenina", "Protectores diarios"}},
		{Link: "https://www.masonline.com.ar/proteccion-femenina/toallitas-higienicas", Categories: []string{"Perfumería", "Protección femenina", "Toallitas"}},
		{Link: "https://www.masonline.com.ar/proteccion-femenina/tampones", Categories: []string{"Perfumería", "Protección femenina", "Tampones"}},
		{Link: "https://www.masonline.com.ar/proteccion-femenina/higiene-femenina", Categories: []string{"Perfumería", "Protección femenina", "Higiene íntima"}},
		{Link: "https://www.masonline.com.ar/algodon/cuidado-personal?map=ft,departamento", Categories: []string{"Perfumería", "Farmacia", "Algodón"}},
		{Link: "https://www.masonline.com.ar/alcohol?_q=alcohol&fuzzy=0&initialMap=ft&initialQuery=alcohol&map=category-1,ft&operator=and&query=/farmacia/alcohol&searchState", Categories: []string{"Perfumería", "Farmacia", "Alcohol"}},
		{Link: "https://www.masonline.com.ar/aposito?_q=aposito&fuzzy=0&initialMap=ft&initialQuery=aposito&map=category-1,ft&operator=and&query=/farmacia/aposito&searchState", Categories: []string{"Perfumería", "Farmacia", "Apósitos"}},
		{Link: "https://www.masonline.com.ar/cuidado-del-adulto/cuidado-sexual", Categories: []string{"Perfumería", "Farmacia", "Preservativos"}},
		{Link: "https://www.masonline.com.ar/accesorios-de-limpieza/baldes-palanganas-y-sopapas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Baldes y Mopas"}},
		{Link: "https://www.masonline.com.ar/papeles-bolsas-y-films/bolsas-hermeticas-y-films", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Bolsas"}},
		{Link: "https://www.masonline.com.ar/broches?_q=broches&map=ft", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Broches y Ganchos"}},
		{Link: "https://www.masonline.com.ar/accesorios-de-limpieza/escobas-y-escobillones", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Escobas y escobillones"}},
		{Link: "https://www.masonline.com.ar/accesorios-de-limpieza/esponjas-y-guantes", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Esponjas y Guantes"}},
		{Link: "https://www.masonline.com.ar/accesorios-de-limpieza/palas-y-cabos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Palas"}},
		{Link: "https://www.masonline.com.ar/accesorios-de-limpieza/trapos-y-pa%C3%B1os", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Paños multiusos"}},
		{Link: "https://www.masonline.com.ar/accesorios-de-limpieza/secadores-y-cepillos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Secadores y Cepillos"}},
		{Link: "https://www.masonline.com.ar/calzado?initialMap=c&initialQuery=calzado&map=category-1,category-2,category-3&query=/calzado/limpiadores-de-calzado-y-pomadas/limpiadores-de-calzado&searchState", Categories: []string{"Limpieza", "Calzado", "Limpiadores"}},
		{Link: "https://www.masonline.com.ar/calzado?initialMap=c&initialQuery=calzado&map=category-1,category-2,category-3&query=/calzado/limpiadores-de-calzado-y-pomadas/pomadas&searchState", Categories: []string{"Limpieza", "Calzado", "Pomadas para calzado"}},
		{Link: "https://www.masonline.com.ar/desodorante-de-ambientes?initialMap=c&initialQuery=desodorante-de-ambientes&map=category-1,category-3&query=/desodorante-de-ambientes/aromatizantes&searchState", Categories: []string{"Limpieza", "Deshodorantes de ambiente", "Aromatizantes"}},
		{Link: "https://www.masonline.com.ar/desodorante-de-ambientes?initialMap=c&initialQuery=desodorante-de-ambientes&map=category-1,category-3,category-3&query=/desodorante-de-ambientes/desinfectantes/desodorantes&searchState", Categories: []string{"Limpieza", "Deshodorantes de ambiente", "Deshodorantes y desinfectantes"}},
		{Link: "https://www.masonline.com.ar/insecticidas/aerosoles", Categories: []string{"Limpieza", "Incecticidas", "Aerosoles"}},
		{Link: "https://www.masonline.com.ar/insecticidas?initialMap=c&initialQuery=insecticidas&map=category-1,category-2&query=/insecticidas/aparatos-y-espirales&searchState", Categories: []string{"Limpieza", "Incecticidas", "Cebos, Bolillas y Pastillas"}},
		{Link: "https://www.masonline.com.ar/insecticidas?initialMap=c&initialQuery=insecticidas&map=category-1,category-2&query=/insecticidas/repelentes&searchState", Categories: []string{"Limpieza", "Incecticidas", "Repelentes"}},
		{Link: "https://www.masonline.com.ar/insecticidas?initialMap=c&initialQuery=insecticidas&map=category-1,category-2&query=/insecticidas/tabletas-y-difusores&searchState", Categories: []string{"Limpieza", "Incecticidas", "Tabletas y difusores"}},
		{Link: "https://www.masonline.com.ar/lavandinas/gel", Categories: []string{"Limpieza", "Lavandinas", "Lavandinas en gel"}},
		{Link: "https://www.masonline.com.ar/lavandinas/liquidas", Categories: []string{"Limpieza", "Lavandinas", "Lavandinas líquidas"}},
		{Link: "https://www.masonline.com.ar/limpieza-de-ba%C3%B1o/desinfectantes-de-bano", Categories: []string{"Limpieza", "Limpieza de baño", "Desinfectantes"}},
		{Link: "https://www.masonline.com.ar/destapaca%C3%B1erias?_q=destapaca%C3%B1erias&map=ft", Categories: []string{"Limpieza", "Limpieza de baño", "Destapa cañerías"}},
		{Link: "https://www.masonline.com.ar/limpieza-de-ba%C3%B1o/pastillas-y-bloques", Categories: []string{"Limpieza", "Limpieza de baño", "Pastillas y bloques"}},
		{Link: "https://www.masonline.com.ar/detergentes?_q=Detergentes&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Detergentes"}},
		{Link: "https://www.masonline.com.ar/escarbadientes?_q=Escarbadientes&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Escarbadientes"}},
		{Link: "https://www.masonline.com.ar/encendedor?_q=encendedor&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Fósforos y encendedores"}},
		{Link: "https://www.masonline.com.ar/fosforo?_q=fosforo&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Fósforos y encendedores"}},
		{Link: "https://www.masonline.com.ar/lavavajillas?_q=lavavajillas&fuzzy=0&initialMap=ft&initialQuery=lavabajillas&map=category-1,ft&operator=and&query=/cocina/lavabajillas&searchState", Categories: []string{"Limpieza", "Limpieza de cocina", "Jabón Lavavajillas"}},
		{Link: "https://www.masonline.com.ar/limpiadores?_q=limpiadores&fuzzy=0&initialMap=ft&initialQuery=limpiadores&map=category-1,ft&operator=and&query=/cocina/limpiadores&searchState", Categories: []string{"Limpieza", "Limpieza de cocina", "LIimpiadores"}},
		{Link: "https://www.masonline.com.ar/velas?_q=velas&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Velas"}},
		{Link: "https://www.masonline.com.ar/ropa?initialMap=c&initialQuery=ropa&map=category-1,category-3&query=/ropa/jabon-en-pan&searchState", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón en pan"}},
		{Link: "https://www.masonline.com.ar/ropa?initialMap=c&initialQuery=ropa&map=category-1,category-3&query=/ropa/jabon-en-polvo&searchState", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón en polvo"}},
		{Link: "https://www.masonline.com.ar/ropa?initialMap=c&initialQuery=ropa&map=category-1,category-3&query=/ropa/jabon-liquido&searchState", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón líquido"}},
		{Link: "https://www.masonline.com.ar/ropa?initialMap=c&initialQuery=ropa&map=category-1,category-2&query=/ropa/suavizantes&searchState", Categories: []string{"Limpieza", "Cuidados de la ropa", "Suavizantes"}},
		{Link: "https://www.masonline.com.ar/ropa?initialMap=c&initialQuery=ropa&map=category-1,category-2&query=/ropa/prelavado-y-quitamanchas&searchState", Categories: []string{"Limpieza", "Cuidados de la ropa", "Quita Manchas"}},
		{Link: "https://www.masonline.com.ar/ropa?initialMap=c&initialQuery=ropa&map=category-1,category-2&query=/ropa/perfume-para-la-ropa-y-aprestos&searchState", Categories: []string{"Limpieza", "Cuidados de la ropa", "Perfumantes"}},
		{Link: "https://www.masonline.com.ar/pisos-y-muebles?initialMap=c&initialQuery=pisos-y-muebles&map=category-1,category-2&query=/pisos-y-muebles/autobrillos-y-ceras&searchState", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Ceras y autobrillos"}},
		{Link: "https://www.masonline.com.ar/pisos-y-muebles?initialMap=c&initialQuery=pisos-y-muebles&map=category-1,category-2&query=/pisos-y-muebles/lustramuebles-y-limpia-metales&searchState", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Lustra muebles"}},
		{Link: "https://www.masonline.com.ar/papeles-bolsas-y-films?initialMap=c&initialQuery=papeles-bolsas-y-films&map=category-1,category-2&query=/papeles-bolsas-y-films/panuelos-descartables&searchState", Categories: []string{"Limpieza", "Papeles", "Pañuelos"}},
		{Link: "https://www.masonline.com.ar/papeles-bolsas-y-films?initialMap=c&initialQuery=papeles-bolsas-y-films&map=category-1,category-2&query=/papeles-bolsas-y-films/papel-higienico&searchState", Categories: []string{"Limpieza", "Papeles", "Papeles higiénicos"}},
		{Link: "https://www.masonline.com.ar/papeles-bolsas-y-films?initialMap=c&initialQuery=papeles-bolsas-y-films&map=category-1,category-2&query=/papeles-bolsas-y-films/rollos-de-cocina&searchState", Categories: []string{"Limpieza", "Papeles", "Rollos de cocina"}},
		{Link: "https://www.masonline.com.ar/papeles-bolsas-y-films?initialMap=c&initialQuery=papeles-bolsas-y-films&map=category-1,category-2&query=/papeles-bolsas-y-films/servilletas-descartables&searchState", Categories: []string{"Limpieza", "Papeles", "Servilletas"}},
		{Link: "https://www.masonline.com.ar/perros/alimentos-y-snacks-perros", Categories: []string{"Mascotas", "Alimentos", "Alimentos"}},
		{Link: "https://www.masonline.com.ar/gatos/alimentos-y-snacks-para-gatos", Categories: []string{"Mascotas", "Alimentos", "Alimentos"}},
	}
}
