package pages_vea

import (
	"comprix/app/domain/dto"
)

func (svc Service) GetCategoryLinks() []dto.ScrapperCategoryLink {
	return []dto.ScrapperCategoryLink{
		{Link: "https://www.vea.com.ar/Almacen/Aceites-y-Vinagres?initialMap=c,c&initialQuery=almacen/aceites-y-vinagres&map=category-1,category-2,category-3,category-3&query=/almacen/aceites-y-vinagres/aceites-comunes/aceites-especiales&searchState", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aceites"}},
		{Link: "https://www.vea.com.ar/Almacen/Aderezos", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aderezos"}},
		{Link: "https://www.vea.com.ar/almacen/aceites-y-vinagres/vinagres", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Vinagres"}},
		{Link: "https://www.vea.com.ar/almacen/aceites-y-vinagres/acetos", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Acheto"}},
		{Link: "https://www.vea.com.ar/Almacen/Arroz-y-Legumbres?initialMap=c,c&initialQuery=almacen/arroz-y-legumbres&map=category-1,category-2,category-3,category-3&query=/almacen/arroz-y-legumbres/arroz/arroz-listos&searchState", Categories: []string{"Almacén", "Arroz y Legumbres", "Arroz"}},
		{Link: "https://www.vea.com.ar/Almacen/Arroz-y-Legumbres?initialMap=c,c&initialQuery=almacen/arroz-y-legumbres&map=category-1,category-2,category-3&query=/almacen/arroz-y-legumbres/legumbres&searchState", Categories: []string{"Almacén", "Arroz y Legumbres", "Legumbres"}},
		{Link: "https://www.vea.com.ar/Almacen/pastas-secas-y-salsas?initialMap=c,c&initialQuery=almacen/pastas-secas-y-salsas&map=category-1,category-2,category-3,category-3,category-3&query=/almacen/pastas-secas-y-salsas/pastas-listas/pastas-secas-guiseras/pastas-secas-largas&searchState", Categories: []string{"Almacén", "Pastas secas", "Pastas secas"}},
		{Link: "https://www.vea.com.ar/almacen/sal-pimienta-y-especias/sal", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Sal"}},
		{Link: "https://www.vea.com.ar/Almacen/Sal-Pimienta-y-Especias?initialMap=c,c&initialQuery=almacen/sal-pimienta-y-especias&map=category-1,category-2,tipo-de-producto&query=/almacen/sal-pimienta-y-especias/pimientas&searchState", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Pimienta"}},
		{Link: "https://www.vea.com.ar/almacen/sal-pimienta-y-especias/especias", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Especias"}},
		{Link: "https://www.vea.com.ar/almacen/conservas/conservas-de-carne", Categories: []string{"Almacén", "Conservas", "Conserva de carne"}},
		{Link: "https://www.vea.com.ar/almacen/conservas/conservas-de-frutas", Categories: []string{"Almacén", "Conservas", "Conserva de frutas"}},
		{Link: "https://www.vea.com.ar/almacen/conservas/conservas-de-pescado", Categories: []string{"Almacén", "Conservas", "Conserva de pescado"}},
		{Link: "https://www.vea.com.ar/almacen/conservas/conservas-de-verduras-y-legumbres", Categories: []string{"Almacén", "Conservas", "Conserva de verduras y legumbres"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/azucar-y-edulcorantes?initialMap=c,c,c&initialQuery=almacen/desayuno-y-merienda/azucar-y-edulcorantes&map=category-1,category-2,category-3,tipo-de-producto,tipo-de-producto,tipo-de-producto&query=/almacen/desayuno-y-merienda/azucar-y-edulcorantes/azucar-impalpable/azucar-negra/azucar-rubia&searchState", Categories: []string{"Almacén", "Desayunos y Meriendas", "Azúcar"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/azucar-y-edulcorantes?initialMap=c,c,c&initialQuery=almacen/desayuno-y-merienda/azucar-y-edulcorantes&map=category-1,category-2,category-3,tipo-de-producto,tipo-de-producto&query=/almacen/desayuno-y-merienda/azucar-y-edulcorantes/edulcorantes-en-polvo/edulcorantes-liquidos&searchState", Categories: []string{"Almacén", "Desayunos y Meriendas", "Edulcorante"}},
		{Link: "https://www.vea.com.ar/bizcochuelos?_q=bizcochuelos&fuzzy=0&initialMap=ft&initialQuery=bizcochuelos&map=ft,tipo-de-producto&operator=and&query=/bizcochuelos/bizcochuelos&searchState", Categories: []string{"Almacén", "Desayunos y Meriendas", "Biscochuelos"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/bizcochuelos-budines-y-magdalenas?initialMap=c,c,c&initialQuery=almacen/desayuno-y-merienda/bizcochuelos-budines-y-magdalenas&map=category-1,category-2,category-3,tipo-de-producto&query=/almacen/desayuno-y-merienda/bizcochuelos-budines-y-magdalenas/budines&searchState", Categories: []string{"Almacén", "Desayunos y Meriendas", "Budines"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/bizcochuelos-budines-y-magdalenas?initialMap=c,c,c&initialQuery=almacen/desayuno-y-merienda/bizcochuelos-budines-y-magdalenas&map=category-1,category-2,category-3,tipo-de-producto&query=/almacen/desayuno-y-merienda/bizcochuelos-budines-y-magdalenas/magdalenas&searchState", Categories: []string{"Almacén", "Desayunos y Meriendas", "Magdalenas"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/cacao-y-saborizantes", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cacao y Saborizantes"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/cafes", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cafes"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/cereales", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cereales"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/galletitas-dulces", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas dulces"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/galletitas-saladas", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas saladas"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/mermeladas-y-jaleas", Categories: []string{"Almacén", "Desayunos y Meriendas", "Mermeladas y dulces"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/piononos", Categories: []string{"Almacén", "Desayunos y Meriendas", "Piononos"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/tes", Categories: []string{"Almacén", "Desayunos y Meriendas", "Tes"}},
		{Link: "https://www.vea.com.ar/almacen/desayuno-y-merienda/yerbas", Categories: []string{"Almacén", "Desayunos y Meriendas", "Yerbas"}},
		{Link: "https://www.vea.com.ar/almacen/harinas/harinas", Categories: []string{"Almacén", "Harinas", "Harinas"}},
		{Link: "https://www.vea.com.ar/almacen/harinas/avenas-y-semolas", Categories: []string{"Almacén", "Harinas", "Avenas y Sémolas"}},
		{Link: "https://www.vea.com.ar/polentas?_q=Polentas&map=ft", Categories: []string{"Almacén", "Harinas", "Polentas"}},
		{Link: "https://www.vea.com.ar/almacen/panificados/lacteados", Categories: []string{"Almacén", "Panificados", "Lacteados"}},
		{Link: "https://www.vea.com.ar/almacen/panificados/pan-para-hamburguesas-y-panchos?initialMap=c,c,c&initialQuery=almacen/panificados/pan-para-hamburguesas-y-panchos&map=category-1,category-2,category-3,tipo-de-producto&query=/almacen/panificados/pan-para-hamburguesas-y-panchos/pan-de-hamburguesa&searchState", Categories: []string{"Almacén", "Panificados", "Pan para hamburguesas"}},
		{Link: "https://www.vea.com.ar/almacen/panificados/pan-para-hamburguesas-y-panchos?initialMap=c,c,c&initialQuery=almacen/panificados/pan-para-hamburguesas-y-panchos&map=category-1,category-2,category-3,tipo-de-producto&query=/almacen/panificados/pan-para-hamburguesas-y-panchos/pan-de-pancho&searchState", Categories: []string{"Almacén", "Panificados", "Pan para panchos"}},
		{Link: "https://www.vea.com.ar/almacen/panificados/tostadas-y-grisines", Categories: []string{"Almacén", "Panificados", "Tostadas y grisines"}},
		{Link: "https://www.vea.com.ar/almacen/panificados/pan-rallado-y-rebozador", Categories: []string{"Almacén", "Panificados", "Pan rallado y rebozador"}},
		{Link: "https://www.vea.com.ar/almacen/panificados/integral-y-salvado", Categories: []string{"Almacén", "Panificados", "Integral y Salvado"}},
		{Link: "https://www.vea.com.ar/almacen/caldos-sopas-pure-y-bolsas-para-horno/caldos", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Caldos"}},
		{Link: "https://www.vea.com.ar/almacen/caldos-sopas-pure-y-bolsas-para-horno/sopas", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Sopas"}},
		{Link: "https://www.vea.com.ar/almacen/caldos-sopas-pure-y-bolsas-para-horno/pure", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Purés"}},
		{Link: "https://www.vea.com.ar/almacen/para-preparar/bizcochuelos-brownies-y-tortas?initialMap=c,c,c&initialQuery=almacen/para-preparar/bizcochuelos-brownies-y-tortas&map=category-1,category-2,category-3,tipo-de-producto&query=/almacen/para-preparar/bizcochuelos-brownies-y-tortas/brownies&searchState", Categories: []string{"Almacén", "Para preparar", "Brownies"}},
		{Link: "https://www.vea.com.ar/almacen/para-preparar/flanes", Categories: []string{"Almacén", "Para preparar", "Flanes"}},
		{Link: "https://www.vea.com.ar/almacen/para-preparar/gelatinas", Categories: []string{"Almacén", "Para preparar", "Gelatinas"}},
		{Link: "https://www.vea.com.ar/almacen/para-preparar/mousse", Categories: []string{"Almacén", "Para preparar", "Mousse"}},
		{Link: "https://www.vea.com.ar/almacen/snacks/frutas-secas-y-disecadas", Categories: []string{"Almacén", "Snacks", "Frutas secas"}},
		{Link: "https://www.vea.com.ar/almacen/snacks/mani", Categories: []string{"Almacén", "Snacks", "Manís"}},
		{Link: "https://www.vea.com.ar/almacen/snacks/nachos", Categories: []string{"Almacén", "Snacks", "Nachos"}},
		{Link: "https://www.vea.com.ar/almacen/snacks/papas-fritas", Categories: []string{"Almacén", "Snacks", "Papas fritas"}},
		{Link: "https://www.vea.com.ar/almacen/snacks/palitos-salados", Categories: []string{"Almacén", "Snacks", "Palitos Salados"}},
		{Link: "https://www.vea.com.ar/almacen/snacks/pochoclos", Categories: []string{"Almacén", "Snacks", "Pochoclos"}},
		{Link: "https://www.vea.com.ar/almacen/golosinas-y-chocolates/alfajores", Categories: []string{"Almacén", "Golosinas y Chocolates", "Alfajores"}},
		{Link: "https://www.vea.com.ar/almacen/golosinas-y-chocolates/bombones", Categories: []string{"Almacén", "Golosinas y Chocolates", "Bombones"}},
		{Link: "https://www.vea.com.ar/almacen/golosinas-y-chocolates/caramelos-y-chicles", Categories: []string{"Almacén", "Golosinas y Chocolates", "Caramelos y chicles"}},
		{Link: "https://www.vea.com.ar/almacen/golosinas-y-chocolates/chocolates", Categories: []string{"Almacén", "Golosinas y Chocolates", "Chocolates"}},
		{Link: "https://www.vea.com.ar/almacen/golosinas-y-chocolates/turrones-y-grageas", Categories: []string{"Almacén", "Golosinas y Chocolates", "Turrones"}},
		{Link: "https://www.vea.com.ar/Bebidas/Cervezas", Categories: []string{"Bebidas", "Cervezas", "Cervezas"}},
		{Link: "https://www.vea.com.ar/Bebidas/Gaseosas", Categories: []string{"Bebidas", "Gaseosas", "Gaseosas"}},
		{Link: "https://www.vea.com.ar/bebidas/jugos/listos", Categories: []string{"Bebidas", "Jugos", "Listos para tomar"}},
		{Link: "https://www.vea.com.ar/bebidas/jugos/en-polvo", Categories: []string{"Bebidas", "Jugos", "En polvo"}},
		{Link: "https://www.vea.com.ar/bebidas/aguas/aguas-con-gas", Categories: []string{"Bebidas", "Aguas", "Aguas con gas"}},
		{Link: "https://www.vea.com.ar/bebidas/aguas/aguas-sin-gas", Categories: []string{"Bebidas", "Aguas", "Aguas sin gas"}},
		{Link: "https://www.vea.com.ar/bebidas/aguas/aguas-saborizadas", Categories: []string{"Bebidas", "Aguas", "Aguas saborizadas"}},
		{Link: "https://www.vea.com.ar/Bebidas/Vinos", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "https://www.vea.com.ar/Bebidas/Isotonicas", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas isotónicas"}},
		{Link: "https://www.vea.com.ar/Bebidas/Energizantes", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas energizantes"}},
		{Link: "https://www.vea.com.ar/Bebidas/Licores", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Licores"}},
		{Link: "https://www.vea.com.ar/Bebidas/Whiskys", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Whiskyes"}},
		{Link: "https://www.vea.com.ar/Bebidas/Bebidas-Blancas", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Bebidas blancas"}},
		{Link: "https://www.vea.com.ar/lacteos/dulce-de-leche", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Dulce de leche", "Dulces de leche"}},
		{Link: "https://www.vea.com.ar/lacteos/cremas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Cremas", "Cremas"}},
		{Link: "https://www.vea.com.ar/lacteos/mantecas-y-margarinas/manteca", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Mantecas"}},
		{Link: "https://www.vea.com.ar/lacteos/mantecas-y-margarinas/margarinas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Margarinas"}},
		{Link: "https://www.vea.com.ar/lacteos/yogures/yogures-enteros", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures enteros"}},
		{Link: "https://www.vea.com.ar/lacteos/yogures/yogures-descremados", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures descremados"}},
		{Link: "https://www.vea.com.ar/yogures%20firmes?_q=Yogures%20Firmes&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures Firmes"}},
		{Link: "https://www.vea.com.ar/lacteos/leches/leches-larga-vida", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches larga vida"}},
		{Link: "https://www.vea.com.ar/lacteos/leches/bebidas-vegetales", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches Vegetales"}},
		{Link: "https://www.vea.com.ar/lacteos/leches/leches-saborizadas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches Infantiles"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/quesos/quesos-untables", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos untables"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/quesos/quesos-rallados", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos rallados"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/quesos/quesos-port-salut-y-cremosos?initialMap=c,c,c&initialQuery=quesos-y-fiambres/quesos/quesos-port-salut-y-cremosos&map=category-1,category-2,category-3,tipo-de-producto&query=/quesos-y-fiambres/quesos/quesos-port-salut-y-cremosos/quesos-port-salut&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos Port salut"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/quesos/quesos-port-salut-y-cremosos?initialMap=c,c,c&initialQuery=quesos-y-fiambres/quesos/quesos-port-salut-y-cremosos&map=category-1,category-2,category-3,tipo-de-producto,tipo-de-producto,tipo-de-producto&query=/quesos-y-fiambres/quesos/quesos-port-salut-y-cremosos/quesos-cheddar/quesos-crema/quesos-cremoso&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos cremosos"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/quesos/ricota", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Ricotas"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/fiambres/jamon-cocido-y-crudo?initialMap=c,c,c&initialQuery=quesos-y-fiambres/fiambres/jamon-cocido-y-crudo&map=category-1,category-2,category-3,tipo-de-producto&query=/quesos-y-fiambres/fiambres/jamon-cocido-y-crudo/jamon-cocido&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Fiambres", "Jamónes cocidos"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/fiambres/jamon-cocido-y-crudo?initialMap=c,c,c&initialQuery=quesos-y-fiambres/fiambres/jamon-cocido-y-crudo&map=category-1,category-2,category-3,tipo-de-producto&query=/quesos-y-fiambres/fiambres/jamon-cocido-y-crudo/jamon-crudo&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Fiambres", "Jamónes crudos"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/salchichas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Embutidos", "Salchichas"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/encurtidos-aceitunas-y-pickles?initialMap=c,c&initialQuery=quesos-y-fiambres/encurtidos-aceitunas-y-pickles&map=category-1,category-2,tipo-de-producto,tipo-de-producto,tipo-de-producto,tipo-de-producto&query=/quesos-y-fiambres/encurtidos-aceitunas-y-pickles/aceitunas-descarozadas/aceitunas-negras/aceitunas-rellenas/aceitunas-verdes&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Aceitunas"}},
		{Link: "https://www.vea.com.ar/quesos-y-fiambres/encurtidos-aceitunas-y-pickles?initialMap=c,c&initialQuery=quesos-y-fiambres/encurtidos-aceitunas-y-pickles&map=category-1,category-2,tipo-de-producto,tipo-de-producto&query=/quesos-y-fiambres/encurtidos-aceitunas-y-pickles/pepinillos/pepinos&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Pickles"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-capilar/shampoo", Categories: []string{"Perfumería", "Cuidado capilar", "Shampoos"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-capilar/acondicionador", Categories: []string{"Perfumería", "Cuidado capilar", "Acondicionadores"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-capilar/reparacion-y-tratamientos", Categories: []string{"Perfumería", "Cuidado capilar", "Tratamientos capilares"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-capilar/fijacion", Categories: []string{"Perfumería", "Cuidado capilar", "Fijadores"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-capilar/coloracion", Categories: []string{"Perfumería", "Cuidado capilar", "Coloración"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-oral/pastas-dentales", Categories: []string{"Perfumería", "Cuidado Oral", "Pastas dentales"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-oral/cepillos-dentales", Categories: []string{"Perfumería", "Cuidado Oral", "Cepillos dentales"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-oral/enjuagues-bucales", Categories: []string{"Perfumería", "Cuidado Oral", "Enjuagues bucales"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-oral/accesorios-dentales", Categories: []string{"Perfumería", "Cuidado Oral", "Accesorios bucales"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-personal/cepillos-y-esponjas", Categories: []string{"Perfumería", "Cuidado personal", "Cepillos y esponjas"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-personal/depilacion", Categories: []string{"Perfumería", "Cuidado personal", "Depilación"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-personal/desodorantes-de-hombres", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes de hombres"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-personal/desodorantes-de-mujer", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes de mujeres"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-personal/desodorantes-y-polvos-pedicos", Categories: []string{"Perfumería", "Cuidado personal", "Talcos"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-personal/jabones", Categories: []string{"Perfumería", "Cuidado personal", "Jabones"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-personal/productos-para-afeitarse", Categories: []string{"Perfumería", "Cuidado personal", "Productos para afeitarse"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-de-la-piel/cremas-corporales", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas corporales"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-de-la-piel/cremas-desmaquillantes", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas desmaquillantes"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-de-la-piel/cremas-faciales", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas faciales"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-de-la-piel/solares-y-post-solares", Categories: []string{"Perfumería", "Cuidado de la piel", "Solares y postsolares"}},
		{Link: "https://www.vea.com.ar/protectores%20diarios?_q=Protectores%20diarios&map=ft", Categories: []string{"Perfumería", "Protección femenina", "Protectores diarios"}},
		{Link: "https://www.vea.com.ar/toallitas%20femenina?_q=toallitas%20femenina&map=ft", Categories: []string{"Perfumería", "Protección femenina", "Toallitas"}},
		{Link: "https://www.vea.com.ar/perfumeria/cuidado-personal/proteccion-femenina?initialMap=c,c,c&initialQuery=perfumeria/cuidado-personal/proteccion-femenina&map=category-1,category-2,category-3,tipo-de-producto&query=/perfumeria/cuidado-personal/proteccion-femenina/tampones&searchState", Categories: []string{"Perfumería", "Protección femenina", "Tampones"}},
		{Link: "https://www.vea.com.ar/perfumeria/farmacia/algodon", Categories: []string{"Perfumería", "Farmacia", "Algodón"}},
		{Link: "https://www.vea.com.ar/perfumeria/farmacia/alcohol", Categories: []string{"Perfumería", "Farmacia", "Alcohol"}},
		{Link: "https://www.vea.com.ar/perfumeria/farmacia/apositos", Categories: []string{"Perfumería", "Farmacia", "Apósitos"}},
		{Link: "https://www.vea.com.ar/perfumeria/farmacia/preservativos", Categories: []string{"Perfumería", "Farmacia", "Preservativos"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/baldes-y-mopas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Baldes y Mopas"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/bolsas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Bolsas"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/broches-y-ganchos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Broches y Ganchos"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/escobas-y-escobillones", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Escobas y escobillones"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/escobillas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Escobillas"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/esponjas-y-guantes", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Esponjas y Guantes"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/palas-y-cabos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Palas"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/panos-multiusos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Paños multiusos"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/secadores-y-cepillos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Secadores y Cepillos"}},
		{Link: "https://www.vea.com.ar/limpieza/accesorios-de-limpieza/trapos-de-piso", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Trapos de piso"}},
		{Link: "https://www.vea.com.ar/limpieza/calzado/brillos-y-revividores", Categories: []string{"Limpieza", "Calzado", "Brillos y revividores"}},
		{Link: "https://www.vea.com.ar/limpieza/calzado/limpiadores", Categories: []string{"Limpieza", "Calzado", "Limpiadores"}},
		{Link: "https://www.vea.com.ar/limpieza/calzado/pomadas-para-calzado", Categories: []string{"Limpieza", "Calzado", "Pomadas para calzado"}},
		{Link: "https://www.vea.com.ar/limpieza/desodorantes-de-ambiente/aromatizantes", Categories: []string{"Limpieza", "Deshodorantes de ambiente", "Aromatizantes"}},
		{Link: "https://www.vea.com.ar/limpieza/desodorantes-de-ambiente/desodorantes-y-desinfectantes", Categories: []string{"Limpieza", "Deshodorantes de ambiente", "Deshodorantes y desinfectantes"}},
		{Link: "https://www.vea.com.ar/limpieza/insecticidas/aerosoles", Categories: []string{"Limpieza", "Incecticidas", "Aerosoles"}},
		{Link: "https://www.vea.com.ar/limpieza/insecticidas/cebos-bolillas-y-pastillas", Categories: []string{"Limpieza", "Incecticidas", "Cebos, Bolillas y Pastillas"}},
		{Link: "https://www.vea.com.ar/limpieza/insecticidas/repelentes", Categories: []string{"Limpieza", "Incecticidas", "Repelentes"}},
		{Link: "https://www.vea.com.ar/limpieza/insecticidas/tabletas-y-difusores", Categories: []string{"Limpieza", "Incecticidas", "Tabletas y difusores"}},
		{Link: "https://www.vea.com.ar/limpieza/lavandina", Categories: []string{"Limpieza", "Lavandinas", "Lavandinas líquidas"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-bano/desinfectantes", Categories: []string{"Limpieza", "Limpieza de baño", "Desinfectantes"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-bano/destapa-canerias", Categories: []string{"Limpieza", "Limpieza de baño", "Destapa cañerías"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-bano/pastillas-y-bloques", Categories: []string{"Limpieza", "Limpieza de baño", "Pastillas y bloques"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-cocina/detergentes", Categories: []string{"Limpieza", "Limpieza de cocina", "Detergentes"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-cocina/escarbadientes", Categories: []string{"Limpieza", "Limpieza de cocina", "Escarbadientes"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-cocina/fosforos", Categories: []string{"Limpieza", "Limpieza de cocina", "Fósforos y encendedores"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-cocina/productos-para-lavavajillas", Categories: []string{"Limpieza", "Limpieza de cocina", "Jabón Lavavajillas"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-cocina/limpiadores", Categories: []string{"Limpieza", "Limpieza de cocina", "LIimpiadores"}},
		{Link: "https://www.vea.com.ar/velas?_q=Velas&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Velas"}},
		{Link: "https://www.vea.com.ar/bolsas%20y%20films?_q=Bolsas%20y%20films&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Bolsas y films"}},
		{Link: "https://www.vea.com.ar/limpieza/cuidado-para-la-ropa/jabon-en-pan", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón en pan"}},
		{Link: "https://www.vea.com.ar/jabon%20en%20polvo?_q=jabon%20en%20polvo&map=ft", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón en polvo"}},
		{Link: "https://www.vea.com.ar/jabon%20liquido?_q=jabon%20liquido&map=ft", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón líquido"}},
		{Link: "https://www.vea.com.ar/limpieza/cuidado-para-la-ropa/suavizantes", Categories: []string{"Limpieza", "Cuidados de la ropa", "Suavizantes"}},
		{Link: "https://www.vea.com.ar/limpieza/cuidado-para-la-ropa/quitamanchas", Categories: []string{"Limpieza", "Cuidados de la ropa", "Quita Manchas"}},
		{Link: "https://www.vea.com.ar/limpieza/cuidado-para-la-ropa/perfumantes", Categories: []string{"Limpieza", "Cuidados de la ropa", "Perfumantes"}},
		{Link: "https://www.vea.com.ar/limpieza/cuidado-para-la-ropa/aprestos-y-blanqueadores", Categories: []string{"Limpieza", "Cuidados de la ropa", "Apréstos"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-pisos-y-muebles/ceras-y-autobrillos", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Ceras y autobrillos"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-pisos-y-muebles/limpiadores-de-pisos", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Limpiadores de piso"}},
		{Link: "https://www.vea.com.ar/limpieza/limpieza-de-pisos-y-muebles/lustramuebles", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Lustra muebles"}},
		{Link: "https://www.vea.com.ar/limpieza/papeles/panuelos", Categories: []string{"Limpieza", "Papeles", "Pañuelos"}},
		{Link: "https://www.vea.com.ar/limpieza/papeles/papel-higienico", Categories: []string{"Limpieza", "Papeles", "Papeles higiénicos"}},
		{Link: "https://www.vea.com.ar/limpieza/papeles/rollos-de-cocina", Categories: []string{"Limpieza", "Papeles", "Rollos de cocina"}},
		{Link: "https://www.vea.com.ar/limpieza/papeles/servilletas", Categories: []string{"Limpieza", "Papeles", "Servilletas"}},
		{Link: "https://www.vea.com.ar/mascotas?initialMap=c&initialQuery=mascotas&map=category-1,category-2,category-2&query=/mascotas/gatos/perros&searchState", Categories: []string{"Mascotas", "Alimentos", "Alimentos"}},
	}
}
