package pages_carrefour

import (
	"comprix/app/domain/dto"
)

func (svc Service) GetCategoryLinks() []dto.ScrapperCategoryLink {
	return []dto.ScrapperCategoryLink{
		{Link: "https://www.carrefour.com.ar/Almacen/Aceites-y-vinagres/Aceites-comunes", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aceites"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Aceites-y-vinagres/Aceites-especiales", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aceites"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Aceites-y-vinagres/Aceites-en-aerosol", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aceites"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Aceites-y-vinagres/Aceites-de-oliva", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aceites"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Sal-aderezos-y-saborizadores/Salsas-y-aderezos", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Aderezos"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Aceites-y-vinagres/Vinagres-acetos-y-limon", Categories: []string{"Almacén", "Aceite, Vinagre y aderezos", "Vinagres"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Arroz-y-legumbres/Arroz", Categories: []string{"Almacén", "Arroz y Legumbres", "Arroz"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Arroz-y-legumbres/Legumbres", Categories: []string{"Almacén", "Arroz y Legumbres", "Legumbres"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Pastas-secas", Categories: []string{"Almacén", "Pastas secas", "Pastas secas"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Sal-aderezos-y-saborizadores/Sal", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Sal"}},
		{Link: "https://www.carrefour.com.ar/almacen/sal-aderezos-y-saborizadores/hierbas-secas-y-especias", Categories: []string{"Almacén", "Sal, Pimienta y Especias", "Especias"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Enlatados-y-Conservas/Conservas-de-frutas", Categories: []string{"Almacén", "Conservas", "Conserva de frutas"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Enlatados-y-Conservas/Conservas-de-pescado", Categories: []string{"Almacén", "Conservas", "Conserva de pescado"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Enlatados-y-Conservas/Conservas-de-legumbres-y-vegetales", Categories: []string{"Almacén", "Conservas", "Conserva de verduras y legumbres"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Azucar-y-endulzantes/Azucar", Categories: []string{"Almacén", "Desayunos y Meriendas", "Azúcar"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Azucar-y-endulzantes/Edulcorantes-y-endulzantes", Categories: []string{"Almacén", "Desayunos y Meriendas", "Edulcorante"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Galletitas-bizcochitos-y-tostadas/Bizcochitos", Categories: []string{"Almacén", "Desayunos y Meriendas", "Biscochuelos"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Budines-y-magdalenas/Budines", Categories: []string{"Almacén", "Desayunos y Meriendas", "Budines"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Budines-y-magdalenas/Magdalenas", Categories: []string{"Almacén", "Desayunos y Meriendas", "Magdalenas"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Infusiones/Cacao", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cacao y Saborizantes"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Cafe", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cafes"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Cereales-y-barritas", Categories: []string{"Almacén", "Desayunos y Meriendas", "Cereales"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Galletitas-bizcochitos-y-tostadas/Galletitas-dulces", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas dulces"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Galletitas-bizcochitos-y-tostadas/Galletitas-de-agua", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas dulces"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Galletitas-bizcochitos-y-tostadas/Galletas-de-arroz", Categories: []string{"Almacén", "Desayunos y Meriendas", "Galletitas dulces"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Mermeladas-y-otros-dulces/Mermeladas-dulces-y-jaleas", Categories: []string{"Almacén", "Desayunos y Meriendas", "Mermeladas y dulces"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Infusiones/Te", Categories: []string{"Almacén", "Desayunos y Meriendas", "Tes"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Yerba", Categories: []string{"Almacén", "Desayunos y Meriendas", "Yerbas"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Harinas/Harinas-comunes-y-leudantes", Categories: []string{"Almacén", "Harinas", "Harinas"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Harinas/Otras-harinas", Categories: []string{"Almacén", "Harinas", "Harinas"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Harinas/Avena", Categories: []string{"Almacén", "Harinas", "Avenas y Sémolas"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Harinas/Polentas", Categories: []string{"Almacén", "Harinas", "Polentas"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Harinas/Premezclas-saladas", Categories: []string{"Almacén", "Harinas", "Pre mezclas"}},
		{Link: "https://www.carrefour.com.ar/panaderia/panificados/panes-lacteados-y-de-mesa", Categories: []string{"Almacén", "Panificados", "Lacteados"}},
		{Link: "https://www.carrefour.com.ar/Panaderia/Panificados/Pan-para-hamburguesas-y-panchos", Categories: []string{"Almacén", "Panificados", "Pan para hamburguesas"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Galletitas-bizcochitos-y-tostadas/Tostadas-grisines-y-marineras", Categories: []string{"Almacén", "Panificados", "Tostadas y grisines"}},
		{Link: "https://www.carrefour.com.ar/Panaderia/Pan-rallado-y-rebozadores", Categories: []string{"Almacén", "Panificados", "Pan rallado y rebozador"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Caldos-sopas-y-pure/Caldos", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Caldos"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Caldos-sopas-y-pure/Sopas", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Sopas"}},
		{Link: "https://www.carrefour.com.ar/Almacen/Caldos-sopas-y-pure/Pures-instantaneos", Categories: []string{"Almacén", "Caldos, Sopas y Purés", "Purés"}},
		{Link: "https://www.carrefour.com.ar/brownies", Categories: []string{"Almacén", "Para preparar", "Brownies"}},
		{Link: "https://www.carrefour.com.ar/tortas", Categories: []string{"Almacén", "Para preparar", "Tortas"}},
		{Link: "https://www.carrefour.com.ar/flanes", Categories: []string{"Almacén", "Para preparar", "Flanes"}},
		{Link: "https://www.carrefour.com.ar/gelatinas", Categories: []string{"Almacén", "Para preparar", "Gelatinas"}},
		{Link: "https://www.carrefour.com.ar/mousse", Categories: []string{"Almacén", "Para preparar", "Mousse"}},
		{Link: "https://www.carrefour.com.ar/frutas%20secas", Categories: []string{"Almacén", "Snacks", "Frutas secas"}},
		{Link: "https://www.carrefour.com.ar/mani", Categories: []string{"Almacén", "Snacks", "Manís"}},
		{Link: "https://www.carrefour.com.ar/almacen/snacks/nachos-mani-y-palitos?fuzzy=0&map=category-1,category-2,category-3,tipo-de-producto&operator=and&order=&query=/almacen/snacks/nachos-mani-y-palitos/nachos", Categories: []string{"Almacén", "Snacks", "Nachos"}},
		{Link: "https://www.carrefour.com.ar/papas%20fritas", Categories: []string{"Almacén", "Snacks", "Papas fritas"}},
		{Link: "https://www.carrefour.com.ar/almacen/snacks/nachos-mani-y-palitos?initialMap=c,c,c&initialQuery=almacen/snacks/nachos-mani-y-palitos&map=category-1,category-2,category-3,tipo-de-producto&order=&query=/almacen/snacks/nachos-mani-y-palitos/palitos-salados&searchState", Categories: []string{"Almacén", "Snacks", "Palitos Salados"}},
		{Link: "https://www.carrefour.com.ar/pochoclos", Categories: []string{"Almacén", "Snacks", "Pochoclos"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Golosinas-y-chocolates/Alfajores", Categories: []string{"Almacén", "Golosinas y Chocolates", "Alfajores"}},
		{Link: "https://www.carrefour.com.ar/bombones", Categories: []string{"Almacén", "Golosinas y Chocolates", "Bombones"}},
		{Link: "https://www.carrefour.com.ar/desayuno-y-merienda/golosinas-y-chocolates/caramelos-gomitas-y-chupetines", Categories: []string{"Almacén", "Golosinas y Chocolates", "Caramelos y chicles"}},
		{Link: "https://www.carrefour.com.ar/Desayuno-y-merienda/Golosinas-y-chocolates/Chocolates", Categories: []string{"Almacén", "Golosinas y Chocolates", "Chocolates"}},
		{Link: "https://www.carrefour.com.ar/turrones?_q=Turrones&map=ft", Categories: []string{"Almacén", "Golosinas y Chocolates", "Turrones"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Cervezas?order=", Categories: []string{"Bebidas", "Cervezas", "Cervezas"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Gaseosas", Categories: []string{"Bebidas", "Gaseosas", "Gaseosas"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Jugos/Jugos-listos", Categories: []string{"Bebidas", "Jugos", "Listos para tomar"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Jugos/Jugos-en-polvo", Categories: []string{"Bebidas", "Jugos", "En polvo"}},
		{Link: "https://www.carrefour.com.ar/bebidas/aguas?fuzzy=0&map=category-1,category-2,tipo-de-producto,tipo-de-producto,tipo-de-producto,tipo-de-producto&operator=and&order=&query=/bebidas/aguas/agua-de-mesa-con-gas/agua-mineral-con-gas/agua-mineralizada-con-gas/soda", Categories: []string{"Bebidas", "Aguas", "Aguas con gas"}},
		{Link: "https://www.carrefour.com.ar/bebidas/aguas?fuzzy=0&map=category-1,category-2,tipo-de-producto,tipo-de-producto,tipo-de-producto&operator=and&order=&query=/bebidas/aguas/agua-de-mesa-sin-gas/agua-mineral-sin-gas/agua-mineralizada-sin-gas", Categories: []string{"Bebidas", "Aguas", "Aguas sin gas"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Aguas/Aguas-saborizadas", Categories: []string{"Bebidas", "Aguas", "Aguas saborizadas"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Vinos", Categories: []string{"Bebidas", "Vinos y espumantes", "Vinos y espumantes"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Bebidas-isotonicas", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas isotónicas"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Bebidas-energizantes", Categories: []string{"Bebidas", "Isotónicas y Energizantes", "Bebidas energizantes"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Bebidas-blancas/Licores", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Licores"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Bebidas-blancas/Whisky", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Whiskyes"}},
		{Link: "https://www.carrefour.com.ar/Bebidas/Bebidas-blancas", Categories: []string{"Bebidas", "Bebidas blancas y Licores", "Bebidas blancas"}},
		{Link: "https://www.carrefour.com.ar/Lacteos-y-productos-frescos/Dulce-de-leche", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Dulce de leche", "Dulces de leche"}},
		{Link: "https://www.carrefour.com.ar/Lacteos-y-productos-frescos/Cremas-de-leche", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Cremas", "Cremas"}},
		{Link: "https://www.carrefour.com.ar/lacteos-y-productos-frescos?map=category-1,tipo-de-producto&order=&query=/lacteos-y-productos-frescos/manteca&searchState", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Mantecas"}},
		{Link: "https://www.carrefour.com.ar/margarinas?_q=Margarinas&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Mantecas y Margarinas", "Margarinas"}},
		{Link: "https://www.carrefour.com.ar/yogures%20enteros?_q=Yogures%20enteros&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures enteros"}},
		{Link: "https://www.carrefour.com.ar/Lacteos-y-productos-frescos/Yogures/Yogures-descremados", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures descremados"}},
		{Link: "https://www.carrefour.com.ar/yogures%20firmes?_q=Yogures%20Firmes&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Yogures", "Yogures Firmes"}},
		{Link: "https://www.carrefour.com.ar/leches%20larga%20vida?_q=Leches%20larga%20vida&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches larga vida"}},
		{Link: "https://www.carrefour.com.ar/Lacteos-y-productos-frescos/Leches/Leches-vegetales", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches Vegetales"}},
		{Link: "https://www.carrefour.com.ar/leches%20infantiles?_q=Leches%20Infantiles&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Leches", "Leches Infantiles"}},
		{Link: "https://www.carrefour.com.ar/Lacteos-y-productos-frescos/Quesos/Quesos-cremas-y-untables", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos untables"}},
		{Link: "https://www.carrefour.com.ar/quesos%20rallados?_q=Quesos%20rallados&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos rallados"}},
		{Link: "https://www.carrefour.com.ar/quesos%20port%20salut?_q=Quesos%20Port%20salut&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos Port salut"}},
		{Link: "https://www.carrefour.com.ar/Lacteos-y-productos-frescos/Quesos/Quesos-cremosos-y-mozzarellas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos cremosos"}},
		{Link: "https://www.carrefour.com.ar/ricotas?_q=Ricotas&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Ricotas"}},
		{Link: "https://www.carrefour.com.ar/Lacteos-y-productos-frescos/Quesos/Quesos-feteados", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Quesos", "Quesos en fetas"}},
		{Link: "https://www.carrefour.com.ar/jam%C3%B3nes%20cocidos?_q=Jam%C3%B3nes%20cocidos&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Fiambres", "Jamónes cocidos"}},
		{Link: "https://www.carrefour.com.ar/jam%C3%B3nes%20crudos?_q=Jam%C3%B3nes%20crudos&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Fiambres", "Jamónes crudos"}},
		{Link: "https://www.carrefour.com.ar/Lacteos-y-productos-frescos/Salchichas", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Embutidos", "Salchichas"}},
		{Link: "https://www.carrefour.com.ar/almacen/enlatados-y-conservas/aceitunas-y-encurtidos?fuzzy=0&map=category-1,category-2,category-3,tipo-de-producto,tipo-de-producto,tipo-de-producto&operator=and&order=&query=/almacen/enlatados-y-conservas/aceitunas-y-encurtidos/aceitunas-negras/aceitunas-rellenas/aceitunas-verdes", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Aceitunas"}},
		{Link: "https://www.carrefour.com.ar/pickles?_q=Pickles&map=ft", Categories: []string{"Lácteos, Fiambres y Encurtidos", "Aceitunas y Pickles", "Pickles"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-del-cabello/Shampoos?order=", Categories: []string{"Perfumería", "Cuidado capilar", "Shampoos"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-del-cabello/Acondicionadores", Categories: []string{"Perfumería", "Cuidado capilar", "Acondicionadores"}},
		{Link: "https://www.carrefour.com.ar/tratamientos%20capilares?_q=Tratamientos%20capilares&map=ft", Categories: []string{"Perfumería", "Cuidado capilar", "Tratamientos capilares"}},
		{Link: "https://www.carrefour.com.ar/fijadores?_q=Fijadores&map=ft", Categories: []string{"Perfumería", "Cuidado capilar", "Fijadores"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-del-cabello/Coloracion", Categories: []string{"Perfumería", "Cuidado capilar", "Coloración"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-dental/Pasta-dental", Categories: []string{"Perfumería", "Cuidado Oral", "Pastas dentales"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-dental/Cepillos-de-dientes", Categories: []string{"Perfumería", "Cuidado Oral", "Cepillos dentales"}},
		{Link: "https://www.carrefour.com.ar/enjuagues%20bucales?_q=Enjuagues%20bucales&map=ft", Categories: []string{"Perfumería", "Cuidado Oral", "Enjuagues bucales"}},
		{Link: "https://www.carrefour.com.ar/accesorios%20bucales?_q=Accesorios%20bucales&map=ft", Categories: []string{"Perfumería", "Cuidado Oral", "Accesorios bucales"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-corporal/Depilacion", Categories: []string{"Perfumería", "Cuidado personal", "Depilación"}},
		{Link: "https://www.carrefour.com.ar/deshodorantes%20de%20hombres?_q=Deshodorantes%20de%20hombres&map=ft", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes de hombres"}},
		{Link: "https://www.carrefour.com.ar/deshodorantes%20de%20mujeres?_q=Deshodorantes%20de%20mujeres&map=ft", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes de mujeres"}},
		{Link: "https://www.carrefour.com.ar/deshodorantes%20infantiles?_q=Deshodorantes%20infantiles&map=ft", Categories: []string{"Perfumería", "Cuidado personal", "Deshodorantes infantiles"}},
		{Link: "https://www.carrefour.com.ar/talcos?_q=Talcos&map=ft", Categories: []string{"Perfumería", "Cuidado personal", "Talcos"}},
		{Link: "https://www.carrefour.com.ar/jabones?_q=Jabones&map=ft", Categories: []string{"Perfumería", "Cuidado personal", "Jabones"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-corporal/Afeitado", Categories: []string{"Perfumería", "Cuidado personal", "Productos para afeitarse"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-de-la-piel/Cremas-corporales", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas corporales"}},
		{Link: "https://www.carrefour.com.ar/desmaquillantes?_q=desmaquillantes&map=ft", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas desmaquillantes"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-de-la-piel/Cremas-faciales", Categories: []string{"Perfumería", "Cuidado de la piel", "Cremas faciales"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Cuidado-de-la-piel/Proteccion-solar", Categories: []string{"Perfumería", "Cuidado de la piel", "Solares y postsolares"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Proteccion-femenina/Protectores-diarios", Categories: []string{"Perfumería", "Protección femenina", "Protectores diarios"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Proteccion-femenina/Toallitas-femeninas", Categories: []string{"Perfumería", "Protección femenina", "Toallitas"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Proteccion-femenina/Tampones", Categories: []string{"Perfumería", "Protección femenina", "Tampones"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Proteccion-femenina/Higiene-intima", Categories: []string{"Perfumería", "Protección femenina", "Higiene íntima"}},
		{Link: "https://www.carrefour.com.ar/perfumeria/algodones-e-hisopos?initialMap=c,c&initialQuery=perfumeria/algodones-e-hisopos&map=category-1,category-2,tipo-de-producto&order=&query=/perfumeria/algodones-e-hisopos/algodon&searchState", Categories: []string{"Perfumería", "Farmacia", "Algodón"}},
		{Link: "https://www.carrefour.com.ar/perfumeria/farmacia/productos-de-farmacia?initialMap=c,c,c&initialQuery=perfumeria/farmacia/productos-de-farmacia&map=category-1,category-2,category-3,tipo-de-producto&order=&query=/perfumeria/farmacia/productos-de-farmacia/alcohol-etilico&searchState", Categories: []string{"Perfumería", "Farmacia", "Alcohol"}},
		{Link: "https://www.carrefour.com.ar/ap%C3%B3sitos?_q=Ap%C3%B3sitos&map=ft", Categories: []string{"Perfumería", "Farmacia", "Apósitos"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Farmacia/Preservativos", Categories: []string{"Perfumería", "Farmacia", "Preservativos"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Articulos-de-limpieza/Baldes-y-palanganas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Baldes y Mopas"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Articulos-de-limpieza/Bolsas-de-residuos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Bolsas"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Articulos-de-limpieza/Escobas-secadores-y-palas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Escobas y escobillones"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Articulos-de-limpieza/Esponjas", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Esponjas y Guantes"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Articulos-de-limpieza/Guantes", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Esponjas y Guantes"}},
		{Link: "https://www.carrefour.com.ar/limpieza/articulos-de-limpieza/trapos-y-panos", Categories: []string{"Limpieza", "Accesorios de Limpieza", "Paños multiusos"}},
		{Link: "https://www.carrefour.com.ar/limpieza/limpieza-de-la-ropa/cuidado-del-calzado", Categories: []string{"Limpieza", "Calzado", "Pomadas para calzado"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Desodorantes-de-ambiente/Desodorantes-y-desinfectantes", Categories: []string{"Limpieza", "Deshodorantes de ambiente", "Deshodorantes y desinfectantes"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Insecticidas", Categories: []string{"Limpieza", "Incecticidas", "Aerosoles"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Lavandinas", Categories: []string{"Limpieza", "Lavandinas", "Lavandinas en gel"}},
		{Link: "https://www.carrefour.com.ar/destapa%20ca%C3%B1er%C3%ADas?_q=Destapa%20ca%C3%B1er%C3%ADas&map=ft", Categories: []string{"Limpieza", "Limpieza de baño", "Destapa cañerías"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-cocina/Detergentes", Categories: []string{"Limpieza", "Limpieza de cocina", "Detergentes"}},
		{Link: "https://www.carrefour.com.ar/escarbadientes?_q=Escarbadientes&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Escarbadientes"}},
		{Link: "https://www.carrefour.com.ar/f%C3%B3sforos?_q=F%C3%B3sforos&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Fósforos y encendedores"}},
		{Link: "https://www.carrefour.com.ar/jab%C3%B3n%20lavavajillas?_q=Jab%C3%B3n%20Lavavajillas&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Jabón Lavavajillas"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-cocina/Limpiadores-cremosos", Categories: []string{"Limpieza", "Limpieza de cocina", "LIimpiadores"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-cocina/Limpiadores-liquidos", Categories: []string{"Limpieza", "Limpieza de cocina", "LIimpiadores"}},
		{Link: "https://www.carrefour.com.ar/velas?_q=Velas&map=ft", Categories: []string{"Limpieza", "Limpieza de cocina", "Velas"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-la-ropa/Jabones-para-la-ropa", Categories: []string{"Limpieza", "Cuidados de la ropa", "Jabón en pan"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-la-ropa/Suavizantes-para-la-ropa", Categories: []string{"Limpieza", "Cuidados de la ropa", "Suavizantes"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-la-ropa/Prelavado-y-quitamanchas", Categories: []string{"Limpieza", "Cuidados de la ropa", "Quita Manchas"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-la-ropa/Perfumantes-para-tela", Categories: []string{"Limpieza", "Cuidados de la ropa", "Perfumantes"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-la-ropa/Aprestos", Categories: []string{"Limpieza", "Cuidados de la ropa", "Apréstos"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-pisos-y-muebles/Autobrillos-y-ceras-para-pisos", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Ceras y autobrillos"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-pisos-y-muebles/Limpiadores-de-piso", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Limpiadores de piso"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Limpieza-de-pisos-y-muebles/Lustramuebles", Categories: []string{"Limpieza", "Limpieza de pisos y muebles", "Lustra muebles"}},
		{Link: "https://www.carrefour.com.ar/Perfumeria/Farmacia/Panuelos-descartables", Categories: []string{"Limpieza", "Papeles", "Pañuelos"}},
		{Link: "https://www.carrefour.com.ar/Limpieza/Papeles-higienicos", Categories: []string{"Limpieza", "Papeles", "Papeles higiénicos"}},
		{Link: "https://www.carrefour.com.ar/limpieza/rollos-de-cocina-y-servilletas?fuzzy=0&map=category-1,category-2,tipo-de-producto&operator=and&order=&query=/limpieza/rollos-de-cocina-y-servilletas/rollo-de-cocina", Categories: []string{"Limpieza", "Papeles", "Rollos de cocina"}},
		{Link: "https://www.carrefour.com.ar/limpieza/rollos-de-cocina-y-servilletas?fuzzy=0&map=category-1,category-2,tipo-de-producto&operator=and&order=&query=/limpieza/rollos-de-cocina-y-servilletas/servilletas-de-papel", Categories: []string{"Limpieza", "Papeles", "Servilletas"}},
		{Link: "https://www.carrefour.com.ar/Mascotas/Alimentos-para-perros", Categories: []string{"Mascotas", "Alimentos", "Alimentos"}},
		{Link: "https://www.carrefour.com.ar/Mascotas/Alimentos-para-gatos", Categories: []string{"Mascotas", "Alimentos", "Alimentos"}},
	}
}
