package service_product

import "strings"

func (svc *Service) FormateUnicodeWords(words string) string {
	for _, group := range svc.GetFormatedUnicodeWords() {
		size := len(group) - 1
		for index, synonym := range group {
			// Omitir ultimo elemento
			if index < size {
				// Reemplaza todas las ocurrencias del sinónimo por el más corto
				words = strings.ReplaceAll(words, synonym, group[index+1])
			}
		}
	}
	// Regresar palabras comprimidas
	return words
}

func (svc *Service) GetFormatedUnicodeWords() [][]string {
	return [][]string{
		[]string{"secador�s p�3�plastico/goma�", "secador doble goma 30 cms la gauchita"},
		[]string{"vais arom dulces sue� rep 450", "repuesto aromatizante para telas vais dulces mimos 500 cc"},

		[]string{"s/", "sin"},
		[]string{"c/", "con"},
		[]string{"x�", "x "},
		[]string{"m�q", "maq"},
		[]string{"el�c", "elec"},
		[]string{"s/a", "sin azucar"},
		[]string{"t�", "te"},
		[]string{"n�5", "n5"},
		[]string{"d�o", "duo"},
		[]string{"n�4", "n4"},
		[]string{"n�51", "n51"},
		[]string{"aim�", "aime"},
		[]string{"ros�", "rose"},
		[]string{"n�52", "n52"},
		[]string{"uni�n", "union"},
		[]string{"bud�n", "budon"},
		[]string{"bid�n", "bidon"},
		[]string{"liq�", "liq "},
		[]string{"�rale", "orale"},
		[]string{"p�sos", "pisos"},
		[]string{"man�", "man"},
		[]string{"n�48", "n48"},
		[]string{"n�8", "n8"},
		[]string{"n�10", "n10"},
		[]string{"beb�", "bebe"},
		[]string{"n�6", "n6"},
		[]string{"n�9", "n9"},
		[]string{"d�a", "dia"},
		[]string{"d�as", "dias"},
		[]string{"a�os", "anos"},
		[]string{"do�a", "dona"},
		[]string{"pi�a", "pina"},
		[]string{"sin�", "sin "},
		[]string{"gas�", "gas "},
		[]string{"caf�", "cafe"},
		[]string{"ca�a", "cana"},
		[]string{"ba�o", "b�o", "ba�", "bano"},
		[]string{"pa�u", "panu"},
		[]string{"mam�", "mama"},
		[]string{"pat�", "pata"},
		[]string{"ci�n", "cion"},
		[]string{"pur�", "pure"},
		[]string{"le�a", "lena"},
		[]string{"bamb�", "bambu"},
		[]string{"ni�os", "ninos"},
		[]string{"anan�", "anana"},
		[]string{"agua�", "agua "},
		[]string{"jam�n", "jamon"},
		[]string{"mo�os", "monos"},
		[]string{"n�7,3", "n7,3"},
		[]string{"pe�on", "penon"},
		[]string{"m�sli", "musli"},
		[]string{"h�ore", "heroe"},
		[]string{"jab�n", "jabon"},
		[]string{"roc�o", "rocio"},
		[]string{"ni�as", "ninas"},
		[]string{"lim�n", "limon"},
		[]string{"pach�", "pacha"},
		[]string{"ca�da", "caida"},
		[]string{"r�pida", "rapida"},
		[]string{"fusi�n", "fusion"},
		[]string{"ayud�n", "ayudin"},
		[]string{"�oquis", "noquis"},
		[]string{"enc�as", "encias"},
		[]string{"�cidos", "acidos"},
		[]string{"white�", "white "},
		[]string{"algod�n", "algodon"},
		[]string{"duram�s", "duramas"},
		[]string{"500mlx12u", "500mlx12u "},
		[]string{"�leos", "oleos"},
		[]string{"nestl�", "nestle"},
		[]string{"block�", "block "},
		[]string{"sand�a", "sandia"},
		[]string{"bomb�n", "bombones"},
		[]string{"crem0s0", ""},
		[]string{"s�samo", "sesamo"},
		[]string{"az�car", "azucar"},
		[]string{"caba�a", "cabana"},
		[]string{"ma�ana", "manana"},
		[]string{"l�quido", "l�q", "liquido"},
		[]string{"h�medo", "humedo"},
		[]string{"pliss�", "pliss "},
		[]string{"souffl�", "souffle"},
		[]string{"cl�sico", "clasico"},
		[]string{"norte�a", "nortena"},
		[]string{"k�tchup", "ketchup"},
		[]string{"peque�o", "pequeno"},
		[]string{"stevia�", "stevia "},
		[]string{"humedo�", "humedo "},
		[]string{"cl�sica", "clasica"},
		[]string{"f�sforos", "fosforos"},
		[]string{"tarag�i", "taragui"},
		[]string{"coraz�n", "corazon"},
		[]string{"s�lido", "solido"},
		[]string{"peque�o", "pequeno"},
		[]string{"or�gano", "oregano"},
		[]string{"azucar�", "azucar "},
		[]string{"guaran�", "guarana"},
		[]string{"casta�o", "castano"},
		[]string{"cofler�", "cofler "},
		[]string{"nescaf�", "nescafe"},
		[]string{"rt5+�", "reparacion total 5"},
		[]string{"maracuy�", "maracuya"},
		[]string{"ca�uelas", "canuelas"},
		[]string{"mineral�", "mineral "},
		[]string{"tallar�n", "tallarin"},
		[]string{"piment�n", "pimenton"},
		[]string{"ma�anita", "mananita"},
		[]string{"clasico�", "clasico "},
		[]string{"espa�ola", "espanola"},
		[]string{"monta�a", "montana"},
		[]string{"pategr�s", "pategras"},
		[]string{"dermagl�s", "dermaglos"},
		[]string{"torront�s", "torrontes"},
		[]string{"hogare�as", "hogarenas"},
		[]string{"tirabuz�n", "tirabuzon"},
		[]string{"higi�nico", "higienico"},
		[]string{"ap�stoles", "apostoles"},
		[]string{"reducci�n", "reduccion"},
		[]string{"bals�mico", "balsamico"},
		[]string{"hellmann�s", "hellmanns"},
		[]string{"sucralosa�", "sucralosa "},
		[]string{"autom�tico", "automatico"},
		[]string{"escobill�n", "escobillon"},
		[]string{"antifrizz�", "antifrizz"},
		[]string{"ecol�gicos", "ecologicos"},
		[]string{"yogur�simo", "yogurisimo"},
		[]string{"garrapi�ada", "garrapinada"},
		[]string{"chocolinas�", "chocolinas "},
		[]string{"instant�neo", "instantaneo"},
		[]string{"carefree�", "carefree "},
		[]string{"liv�edulco�", "liv edulco "},
		[]string{"n�", "n"},
		[]string{"cl�si", "clasi"},
		[]string{"coraz�", ""},
		[]string{"tamp�n", "tampon"},
		[]string{"el�stica", "elastica"},
		[]string{"pa�o", "pano"},
		[]string{"f�cil", "facil"},
		[]string{"u�a", "una"},
		[]string{"h�roe", "heroe"},
		[]string{"com�n", "comun"},
		[]string{"a�o", "ano"},
	}
}
