package service_product

import (
	"strings"
)

func (svc *Service) ZipWords(words string) string {
	for _, group := range svc.GetZippedWords() {
		size := len(group) - 1
		for index, synonym := range group {
			// Omitir ultimo elemento
			if index < size {
				// Reemplaza todas las ocurrencias del sinónimo por el más corto
				words = strings.ReplaceAll(words, synonym, group[index+1])
			}
		}
	}
	// Regresar palabras comprimidas
	return words
}

func (svc *Service) GetZippedWords() [][]string {
	return [][]string{
		[]string{"vino blanco dulce", "vino dulce blanco"},
		[]string{"fino cepa tradicional tinto", "malbec cepa tradicional"},
		[]string{"tardio blanco", "tardio blanco dulce"},
		[]string{"fuerza reparadora", "reparador esencia", "restauracion", "reparador"},
		[]string{"amalaya blanco", "amalaya blanco dulce"},
		[]string{"concentrado de telas", "concentrado"},
		[]string{"sopa cup", "pasta cup", "cup"},
		[]string{"milkaut cremoso", "milkaut colchon", "milkaut"},
		// Limpiar
		[]string{" suave ", " "},
		[]string{"aderezo", ""},
		[]string{"con palo", ""},
		[]string{"con acido", ""},
		[]string{" firme ", " "},
		[]string{"ser cereales", "ser"},
		[]string{"gel natural", "gel hot", "geles", " gel ", ""},
		[]string{"pcv", "pvc", " "},
		[]string{"gaseosa cola", ""},
		[]string{"extra virgen", ""},
		[]string{"vitamina c", "vit c", ""},
		[]string{"vitamina a", "vit a", ""},
		[]string{"virgen extra", ""},
		// Palabras complejas
		[]string{"mms", "mm"},
		[]string{"queso blanco", "queso"},
		[]string{"colgate", "total"},
		[]string{"listo knorr", "knorr"},
		[]string{"ades soja", "ades"},
		[]string{"feteado", "en fetas"},
		[]string{"jabon en barra", "jabon"},
		[]string{"bebida isotonica", "isotonica"},
		[]string{"birghton", "brighton"},
		[]string{"milakut", "milkaut", "mil"},
		[]string{"mini gel", "minigel"},
		[]string{"sin piel", "pelado"},
		[]string{"merlight", "mer light"},
		[]string{"dvcatena", "dv catena"},
		[]string{"sauvnion", "sauvignon"},
		[]string{" prov v ", "prov"},
		[]string{"dedalito", "dedal"},
		[]string{"caserito", "caser"},
		[]string{"cereales", "cerealitas", "cereal"},
		[]string{"tallarin", "talla"},
		[]string{"cabernet", "cabernet sauvignon", "carnet"},
		[]string{"huevo don", "don"},
		[]string{"atun lomo", "atun"},
		[]string{"laddu bar", "laddubar"},
		[]string{"limon ama", "limon"},
		[]string{"confitados", "confites"},
		[]string{"retornable", "ret", ""},
		[]string{"endulzante", "edulcorante"},
		[]string{"sin azucar", "sinazucar", "zero"},
		[]string{"cunnington", "cunning"},
		[]string{"yerba mate", "yerba"},
		[]string{"mate tradicional", "yerba tradicional"},
		[]string{"integrales", "integral"},
		[]string{"mango loco", "mango"},
		[]string{"granagua", "gran agua granix"},
		[]string{"vainillachocolate", "vainilla chocolate"},
		[]string{"galletitas de agua", "galletitas dulces", "galletitas queso", "galletitas", "galletita", "galletas", "galleta", "gall"},
		[]string{"vino tinto", "vino tino", "vino blanco", "vino fino", "vino"},
		[]string{"multicereal", "multicer"},
		[]string{"saborizador", "sazonador"},
		[]string{"fina salero", "fina"},
		[]string{"garoto caja", "garoto"},
		[]string{"gaseosa coca", "coca"},
		[]string{"pasta carne", "carne"},
		[]string{"levite cero", "levite"},
		[]string{"ketchup hot", "ketchup"},
		[]string{"jugo cepita", "cepita"},
		[]string{"chivas regal", "chivas"},
		[]string{"revilitacion", "revitalizacion"},
		[]string{"rubia stella", "stella"},
		[]string{"nescafe gold", "cafe nescafe gold"},
		[]string{"tuco y guiso", "tuco"},
		[]string{"dorado anejo", "anejo"},
		[]string{"imperial ipa", "imperial lager", "imperial"},
		[]string{"agua de mesa", "agua"},
		[]string{"pasta dental", "crema dental"},
		[]string{"limon cremoso", "limon"},
		[]string{"aceite y agua", "aceite"},
		[]string{"alfajor negro", "alfajor"},
		[]string{"pasta sardina", "sardina"},
		[]string{"adultos gatos", "adultos pavo", "adultos"},
		[]string{"platinum plus", "platinum"},
		[]string{"brewing nitro", "brewing"},
		[]string{"elvive protec", "elvive", "elv"},
		[]string{"surtidos caja", "surtidos"},
		[]string{"gallo parboil", "parboil gallo oro"},
		[]string{"whiskas gatos", "whiskas"},
		[]string{"rubia clasica", "clasica"},
		[]string{"reales buenas", "buenas"},
		[]string{"agua saborizada", "saborizada"},
		[]string{"harina de trigo", "harina"},
		[]string{"flor de sevilla", "sevilla"},
		[]string{"vino pia", "pia"},
		[]string{"vino pinot", "pinot"},
		[]string{"te hierbas", "te"},
		[]string{"manzana roja", "manzana"},
		[]string{"licor crema", "licor"},
		[]string{"jugo en polvo", "jugo"},
		[]string{"vino espumante", "espumante"},
		[]string{"vino don david", "don david"},
		[]string{"vodka smirnoff", "smirnoff"},
		[]string{"rosamonte plus", "rosamonte"},
		[]string{"crema de leche", "crema"},
		[]string{"bebida vegetal", "bebida"},
		[]string{"lavandinacloro", "lavandina"},
		[]string{"negra guinness", "guinness"},
		[]string{"enjuague bucal", "enjuague"},
		[]string{"heineken lager", "heineken"},
		[]string{"razas pequenas", "pequenos"},
		[]string{"sauvignon syrah", "sauvignon"},
		[]string{"reparacion coco", "reparacion"},
		[]string{"trigo matarazzo", "matarazzo", "matarazz"},
		[]string{"schneider lager", "schneider"},
		[]string{"sabrositos gato", "sabrositos para gatos", "sabrositos"},
		[]string{"polvo chocolino", "chocolino"},
		[]string{"crema casancrem", "casancrem"},
		[]string{"estate organico", "organico"},
		[]string{"carbon activado", "carbon"},
		[]string{"detox antifrizz", "detox capilar"},
		[]string{"intocables black", "intocables"},
		[]string{"frescura intensa", "intensa"},
		[]string{"hierbas serranas", "hierbas"},
		[]string{"arroz prep gallo", "arroz gallo"},
		[]string{"para gato adulto", "para adulto"},
		[]string{"cepita del valle", "cepita"},
		[]string{"aceitunas verdes", "aceitunas"},
		[]string{"cafe choco mocha", "cafe nescafe choco mocha"},
		[]string{"plusbelle esencia", "plusbelle"},
		[]string{"starbucks veranda", "cafe veranda starbucks"},
		[]string{"agua mineralizada", "agua mineral", "agua"},
		[]string{"premezcla cookies", "cookies"},
		[]string{"ipa lata imperial", "imperial"},
		[]string{"margarina vegetal", "margarina"},
		[]string{"salsa chimichurri", "chimichurri"},
		[]string{"salsa la parmesana", "la parmesana"},
		[]string{"detergente cremoso", "detergente"},
		[]string{"serenisima clasico", "serenisima"},
		[]string{"cepillo de dientes", "cepillo dental"},
		[]string{"cepillo proteccion", "cepillo dental proteccion"},
		[]string{"caldo verdura maggi", "caldo verdura"},
		// []string{"la virginia hierbas", "la virginia"},
		[]string{"aceite aromatizante", "aceites"},
		[]string{"autobrillo Incoloro", "autobrillo"},
		[]string{"tratamiento capilar", "tratamiento"},
		[]string{"alimento para gatos", "alimento para gato", "alimento gatos", "alimento"},
		[]string{"alimento para perros", "alimento para perro", "alimento perros", "alimento"},
		[]string{"seleccion de vinedos", "seleccion"},
		[]string{"natural deslactosado", "naturalcon", "natural"},
		[]string{"gaseosa naranja fanta", "naranja fanta"},
		[]string{"merlot saint felicien", "saint felicien"},
		[]string{"cerveza roja patagonia", "cerveza patagonia"},
		[]string{"aerosol mazola manteca", "girasol manteca mazola"},
		[]string{"limpiador desinfectante", "desinfectante"},
		[]string{"alimento seco para perro", "alimento seco"},
		[]string{"smirnoff spicy tamarindo", "smirnoff tamarindo"},
		// Con espacios
		[]string{" uno ", " i "},
		[]string{"aji ", "ija "},
		[]string{"ajo ", "oja "},
		[]string{"roja ", "red "},
		// Comprimir palabras
		[]string{"ave", "a"},
		[]string{"csbe", "cbse"},
		[]string{"bano", "bno"},
		[]string{"food", "fd"},
		[]string{"salsa", "ssa"},
		[]string{"hair", "hr"},
		[]string{"queso", "q"},
		[]string{"extra", "e"},
		[]string{"polvo", "plvo"},
		[]string{"liviano", "light", "lig"},
		[]string{"huevo", "huev"},
		[]string{"menta fresca", "menta", "mint"},
		[]string{"ebrut", "e brut"},
		[]string{"varietal", "var"},
		[]string{"rigatti", "rigat"},
		[]string{"gomitas", "gomas"},
		[]string{"fideos cinta", "fideos", "fideo", "fid"},
		[]string{"tinto", "tto"},
		[]string{"sobre", "st"},
		[]string{"jabon", "jab"},
		[]string{"bolsa", "botella", " x "},
		[]string{"dolca", "dlc"},
		[]string{"frito", "fr"},
		[]string{"frutas", "fr"},
		[]string{"entero", "ent"},
		[]string{"cocina", "coc"},
		[]string{"muesli", "musli"},
		[]string{"poroto", "porotos", "poro"},
		[]string{"aceite", "aceit", "ac"},
		[]string{"helado", "hel"},
		[]string{"sesamo", "ses"},
		[]string{"molido", "mol"},
		[]string{"negras ", "ne "},
		[]string{"fijador", "fija", "fij"},
		[]string{"aireado", "air"},
		[]string{"souffle", "soufle", "sffe"},
		[]string{"adultos", "adulto", "adto"},
		[]string{"maquina", "maq"},
		[]string{"fructis", "frci"},
		[]string{"shampoo", "sh"},
		[]string{"naranja", "naranj", "nja"},
		[]string{"bebible", "beb"},
		[]string{"cortado", "cortd"},
		[]string{"natural", "natura", "nat"},
		[]string{"durazno", "duraz", "dur"},
		[]string{"peonias", "peon"},
		[]string{"nescafe", "nesc"},
		[]string{"ciruela", "cirue"},
		[]string{"cerlmat", "cereal"},
		[]string{"cebolla", "ceb"},
		[]string{"gaseosa", "gas"},
		[]string{"cerveza", "cervez", "cerv"},
		[]string{"manzana", "manz"},
		[]string{"sixpack", "six"},
		[]string{"liquido", "liq"},
		[]string{"keratin", "ke"},
		[]string{"monster", "monst"},
		[]string{"la casa", "lacasa"},
		[]string{"capitulo", "cap"},
		[]string{"bombones", "bombon"},
		[]string{"alicante", "alicant"},
		[]string{"garbanzo", "garb"},
		[]string{"jalapeno", "jalap"},
		[]string{"merengue", "mermelada", "mermel", "merm", "mer"},
		[]string{"vainilla", "vain", "vai"},
		[]string{"ravioles", "raviol", "rav"},
		[]string{"milanesa", "milan", "mila"},
		[]string{"vitaminas", "vitamina", "vit"},
		[]string{"repuesto", "rep"},
		[]string{"maracuya", "mar"},
		[]string{"frutilla", "frut"},
		[]string{"reducido", "red"},
		[]string{"lucchetti", "lucc"},
		[]string{"balsamico", "bals", "bal"},
		[]string{"exquisita", "exq"},
		[]string{"frambuesa", "framb"},
		[]string{"premezcla", "prem"},
		[]string{"electrico", "elec"},
		[]string{"espumante", "espumant", "espuman", "espum"},
		[]string{"limpiador", "limp"},
		[]string{"cormillot", "cormi", "corm"},
		[]string{"arandanos", "arandano", "arand"},
		[]string{"mandarina", "manda"},
		[]string{"detergente", "det"},
		[]string{"yogur descremado", "yogur ", " yogurt ", " yog "},
		[]string{"seleccion", "selec"},
		[]string{"yogurisimo", "yoguris", "yogurs"},
		[]string{"fettuccini", "fetuc"},
		[]string{"mozzarella", "mozza", "mozz"},
		[]string{"servilleta", "ser"},
		[]string{"cappuccino", "cappu"},
		[]string{"descremado", "desc", ""},
		[]string{"tradicional", "trad"},
		[]string{"instantaneo", "inst"},
		[]string{"cremoso", "crema", "crem", "cr", ""},
		[]string{"energizante", "energ"},
		[]string{"tiburoncito", "tiburon"},
		[]string{"prebioticos", "prebiotica", "prebiot"},
		[]string{"edulcorante", "edulco"},
		[]string{"deslactosado", "deslac"},
		[]string{"aromatizante", "arom"},
		[]string{"pampa gourmet", "pampagourmet", "pampag", "ppg"},
		[]string{"acondicionador", "acodicionador", "acond", "aco", "ac"},
		//
		[]string{"glade", "gld"},
		[]string{"aceites", "aceite"},
	}
}
